#!/usr/bin/env python3
"""6-DOF pose detection for ArUco/AprilTag cubes generated by generate_cube.py.

Loads cube geometry from config.json (produced by generate_cube.py),
detects markers in camera/image/video, and estimates the cube's 6-DOF pose.
"""

import argparse
import json
import sys
import time

import cv2
import numpy as np

from generate_cube import CubeConfig, DICT_MAP, FACE_DEFS


# ---------------------------------------------------------------------------
# Load cube config from JSON
# ---------------------------------------------------------------------------
def load_cube_config(path: str) -> tuple[CubeConfig, dict[str, set[int]]]:
    """Load CubeConfig and face→tag mapping from config.json."""
    with open(path) as f:
        data = json.load(f)

    from generate_cube import parse_grid
    gx, gy, gz = parse_grid(data["grid"])
    dict_id = DICT_MAP[data["dict"]]

    config = CubeConfig(
        grid_x=gx, grid_y=gy, grid_z=gz,
        dict_id=dict_id, dict_name=data["dict"],
        tag_ids=data["tag_ids"],
        tag_size_mm=data["tag_size_mm"],
        margin_cells=data["margin_cells"],
        border_cells=data["border_cells"],
        cell_size_mm=data["cell_size_mm"],
    )
    config.compute()

    face_id_sets = {name: set(ids) for name, ids in data["faces"].items()}
    return config, face_id_sets


# ---------------------------------------------------------------------------
# 3D model: tag_id → corner positions on cube surface
# ---------------------------------------------------------------------------
def build_tag_corner_map(config: CubeConfig) -> dict[int, np.ndarray]:
    """Build mapping from tag_id to 3D corner positions (4x3, mm).

    Corners are ordered [TL, TR, BR, BL] as seen from outside the face,
    matching cv2.aruco.detectMarkers() corner ordering.
    """
    tag_corner_map: dict[int, np.ndarray] = {}
    id_cursor = 0
    mp = config.marker_pixels
    cs = config.cell_size

    for face_def in FACE_DEFS:
        _name, normal_ax, normal_sign, right_ax, right_sign, down_ax, down_sign = face_def
        face_rows, face_cols, down_cells, right_cells = config.face_layout(face_def)
        n_tags = face_rows * face_cols

        # Centering offsets (same logic as build_face_grid in generate_cube.py)
        tag_block_w = face_cols * mp + max(0, face_cols - 1) * config.margin_cells
        tag_block_h = face_rows * mp + max(0, face_rows - 1) * config.margin_cells
        row_off = (down_cells - tag_block_h) // 2
        col_off = (right_cells - tag_block_w) // 2

        right_half = config.box_dims[right_ax] / 2.0
        down_half = config.box_dims[down_ax] / 2.0
        face_pos = normal_sign * config.box_dims[normal_ax] / 2.0

        def cell_to_3d(row: float, col: float) -> np.ndarray:
            u = right_sign * (-right_half + col * cs)
            v = down_sign * (-down_half + row * cs)
            pt = np.zeros(3)
            pt[normal_ax] = face_pos
            pt[right_ax] = u
            pt[down_ax] = v
            return pt

        for r in range(face_rows):
            for c in range(face_cols):
                idx = r * face_cols + c
                if id_cursor + idx >= len(config.tag_ids):
                    break
                tag_id = config.tag_ids[id_cursor + idx]

                rs = row_off + r * (mp + config.margin_cells)
                cc = col_off + c * (mp + config.margin_cells)

                # [TL, TR, BR, BL] as seen from outside
                corners_3d = np.array([
                    cell_to_3d(rs, cc),            # TL
                    cell_to_3d(rs, cc + mp),       # TR
                    cell_to_3d(rs + mp, cc + mp),  # BR
                    cell_to_3d(rs + mp, cc),       # BL
                ], dtype=np.float64)

                tag_corner_map[tag_id] = corners_3d

        id_cursor += n_tags

    return tag_corner_map




# ---------------------------------------------------------------------------
# ArUco detector with tuned parameters
# ---------------------------------------------------------------------------
def create_detector(dict_id: int) -> cv2.aruco.ArucoDetector:
    """Create an ArUco detector tuned for 3D-printed markers."""
    dictionary = cv2.aruco.getPredefinedDictionary(dict_id)
    params = cv2.aruco.DetectorParameters()

    # Sub-pixel corner refinement — critical for PnP accuracy
    params.cornerRefinementMethod = cv2.aruco.CORNER_REFINE_SUBPIX
    params.cornerRefinementWinSize = 5
    params.cornerRefinementMaxIterations = 50
    params.cornerRefinementMinAccuracy = 0.01

    # Adaptive thresholding — wider range for 3D-printed surface texture
    params.adaptiveThreshWinSizeMin = 3
    params.adaptiveThreshWinSizeMax = 53
    params.adaptiveThreshWinSizeStep = 4

    # Candidate filtering — relax for oblique views
    params.minMarkerPerimeterRate = 0.01
    params.maxMarkerPerimeterRate = 4.0
    params.polygonalApproxAccuracyRate = 0.05
    params.minCornerDistanceRate = 0.02
    params.minDistanceToBorder = 1

    # Bit decoding — higher sampling for oblique perspectives
    params.perspectiveRemovePixelPerCell = 8
    params.perspectiveRemoveIgnoredMarginPerCell = 0.13

    params.errorCorrectionRate = 0.6

    return cv2.aruco.ArucoDetector(dictionary, params)


# ---------------------------------------------------------------------------
# Pose estimation
# ---------------------------------------------------------------------------
def estimate_pose(
    object_points: np.ndarray,
    image_points: np.ndarray,
    camera_matrix: np.ndarray,
    dist_coeffs: np.ndarray,
    prev_rvec: np.ndarray | None = None,
    prev_tvec: np.ndarray | None = None,
) -> tuple[bool, np.ndarray | None, np.ndarray | None, float, np.ndarray | None]:
    """Estimate 6-DOF pose from 2D-3D correspondences.

    Returns (success, rvec, tvec, reproj_error, inliers).
    """
    n_points = object_points.shape[0]
    if n_points < 4:
        return False, None, None, float("inf"), None

    use_guess = prev_rvec is not None and prev_tvec is not None

    if n_points >= 6:
        success, rvec, tvec, inliers = cv2.solvePnPRansac(
            objectPoints=object_points,
            imagePoints=image_points,
            cameraMatrix=camera_matrix,
            distCoeffs=dist_coeffs,
            rvec=prev_rvec.copy() if use_guess else None,
            tvec=prev_tvec.copy() if use_guess else None,
            useExtrinsicGuess=use_guess,
            iterationsCount=200,
            reprojectionError=3.0,
            confidence=0.99,
            flags=cv2.SOLVEPNP_SQPNP,
        )
    else:
        success, rvec, tvec = cv2.solvePnP(
            objectPoints=object_points,
            imagePoints=image_points,
            cameraMatrix=camera_matrix,
            distCoeffs=dist_coeffs,
            rvec=prev_rvec.copy() if use_guess else None,
            tvec=prev_tvec.copy() if use_guess else None,
            useExtrinsicGuess=use_guess,
            flags=cv2.SOLVEPNP_SQPNP,
        )
        inliers = np.arange(n_points).reshape(-1, 1) if success else None

    if not success:
        return False, None, None, float("inf"), None

    # Refine with Levenberg-Marquardt on inliers
    if inliers is not None and len(inliers) >= 4:
        idx = inliers.flatten()
        rvec, tvec = cv2.solvePnPRefineLM(
            objectPoints=object_points[idx],
            imagePoints=image_points[idx],
            cameraMatrix=camera_matrix,
            distCoeffs=dist_coeffs,
            rvec=rvec,
            tvec=tvec,
        )

    # Reprojection error
    projected, _ = cv2.projectPoints(object_points, rvec, tvec, camera_matrix, dist_coeffs)
    projected = projected.reshape(-1, 2)
    reproj_err = float(np.mean(np.linalg.norm(image_points - projected, axis=1)))

    return success, rvec, tvec, reproj_err, inliers


# ---------------------------------------------------------------------------
# Temporal filter
# ---------------------------------------------------------------------------
class PoseFilter:
    """EMA filter for smoothing pose in video."""

    def __init__(self, alpha: float = 0.3, max_jump_mm: float = 50.0,
                 max_jump_deg: float = 30.0):
        self.alpha = alpha
        self.max_jump_mm = max_jump_mm
        self.max_jump_deg = max_jump_deg
        self.rvec: np.ndarray | None = None
        self.tvec: np.ndarray | None = None

    def update(self, rvec: np.ndarray, tvec: np.ndarray
               ) -> tuple[np.ndarray, np.ndarray]:
        if self.rvec is None:
            self.rvec = rvec.copy()
            self.tvec = tvec.copy()
            return self.rvec.copy(), self.tvec.copy()

        dt = float(np.linalg.norm(tvec - self.tvec))
        R_prev, _ = cv2.Rodrigues(self.rvec)
        R_curr, _ = cv2.Rodrigues(rvec)
        R_diff = R_curr @ R_prev.T
        angle = np.arccos(np.clip((np.trace(R_diff) - 1) / 2, -1, 1))
        angle_deg = float(np.degrees(angle))

        if dt > self.max_jump_mm or angle_deg > self.max_jump_deg:
            self.rvec = rvec.copy()
            self.tvec = tvec.copy()
        else:
            self.tvec = self.alpha * tvec + (1 - self.alpha) * self.tvec
            self.rvec = self.alpha * rvec + (1 - self.alpha) * self.rvec

        return self.rvec.copy(), self.tvec.copy()

    def reset(self):
        self.rvec = None
        self.tvec = None


# ---------------------------------------------------------------------------
# Main estimator
# ---------------------------------------------------------------------------
class CubePoseEstimator:
    """Detects ArUco tags on a cube and estimates 6-DOF pose."""

    def __init__(self, config: CubeConfig, face_id_sets: dict[str, set[int]],
                 camera_matrix: np.ndarray, dist_coeffs: np.ndarray,
                 enable_filter: bool = True):
        self.config = config
        self.camera_matrix = camera_matrix
        self.dist_coeffs = dist_coeffs

        self.tag_corner_map = build_tag_corner_map(config)
        self.valid_ids = set(self.tag_corner_map.keys())
        self.face_id_sets = face_id_sets
        self.detector = create_detector(config.dict_id)
        self.pose_filter = PoseFilter() if enable_filter else None

        self.prev_rvec: np.ndarray | None = None
        self.prev_tvec: np.ndarray | None = None

        # Box wireframe corners for visualization
        bx, by, bz = config.box_dims
        hx, hy, hz = bx / 2, by / 2, bz / 2
        self.box_corners_3d = np.array([
            [-hx, -hy, -hz], [+hx, -hy, -hz], [+hx, +hy, -hz], [-hx, +hy, -hz],
            [-hx, -hy, +hz], [+hx, -hy, +hz], [+hx, +hy, +hz], [-hx, +hy, +hz],
        ], dtype=np.float64)
        self.box_edges = [
            (0, 1), (1, 2), (2, 3), (3, 0),  # bottom
            (4, 5), (5, 6), (6, 7), (7, 4),  # top
            (0, 4), (1, 5), (2, 6), (3, 7),  # verticals
        ]

    def process_frame(self, image: np.ndarray) -> dict:
        """Process a single frame and return pose result."""
        result = {
            "success": False, "rvec": None, "tvec": None,
            "reproj_error": float("inf"), "n_tags": 0,
            "n_inliers": 0, "detections": [], "tag_ids": [],
            "visible_faces": set(),
        }

        # Detect
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) if len(image.shape) == 3 else image
        corners_list, ids, _ = self.detector.detectMarkers(gray)
        if ids is None:
            self.prev_rvec = None
            self.prev_tvec = None
            if self.pose_filter:
                self.pose_filter.reset()
            return result

        # Filter to valid cube IDs
        detections = []
        for i in range(len(ids)):
            tag_id = int(ids[i][0])
            if tag_id in self.valid_ids:
                corners_2d = corners_list[i].reshape(4, 2)
                detections.append((tag_id, corners_2d))

        result["detections"] = detections
        result["n_tags"] = len(detections)
        result["tag_ids"] = [d[0] for d in detections]

        if not detections:
            self.prev_rvec = None
            self.prev_tvec = None
            if self.pose_filter:
                self.pose_filter.reset()
            return result

        # Identify visible faces
        for tag_id, _ in detections:
            for face_name, id_set in self.face_id_sets.items():
                if tag_id in id_set:
                    result["visible_faces"].add(face_name)

        # Aggregate 2D-3D correspondences
        obj_pts = []
        img_pts = []
        for tag_id, corners_2d in detections:
            obj_pts.append(self.tag_corner_map[tag_id])
            img_pts.append(corners_2d)
        object_points = np.vstack(obj_pts).astype(np.float64)
        image_points = np.vstack(img_pts).astype(np.float64)

        # Solve PnP
        success, rvec, tvec, reproj_err, inliers = estimate_pose(
            object_points, image_points,
            self.camera_matrix, self.dist_coeffs,
            self.prev_rvec, self.prev_tvec,
        )

        if not success or reproj_err > 5.0:
            self.prev_rvec = None
            self.prev_tvec = None
            if self.pose_filter:
                self.pose_filter.reset()
            return result

        # Temporal filter
        if self.pose_filter:
            rvec, tvec = self.pose_filter.update(rvec, tvec)

        self.prev_rvec = rvec.copy()
        self.prev_tvec = tvec.copy()

        result["success"] = True
        result["rvec"] = rvec
        result["tvec"] = tvec
        result["reproj_error"] = reproj_err
        result["n_inliers"] = len(inliers) if inliers is not None else 0
        return result

    def draw_result(self, image: np.ndarray, result: dict) -> np.ndarray:
        """Draw detected markers, axes, and wireframe."""
        vis = image.copy()

        # Draw detected markers
        if result["detections"]:
            corners = [d[1].reshape(1, 4, 2).astype(np.float32) for d in result["detections"]]
            ids_arr = np.array([[d[0]] for d in result["detections"]])
            cv2.aruco.drawDetectedMarkers(vis, corners, ids_arr)

        if result["success"]:
            rvec, tvec = result["rvec"], result["tvec"]

            # Draw coordinate axes at cube center
            axis_len = float(max(self.config.box_dims) / 2)
            cv2.drawFrameAxes(vis, self.camera_matrix, self.dist_coeffs,
                              rvec, tvec, axis_len, 3)

            # Draw box wireframe
            projected, _ = cv2.projectPoints(
                self.box_corners_3d, rvec, tvec,
                self.camera_matrix, self.dist_coeffs,
            )
            pts = projected.reshape(-1, 2).astype(int)
            for i, j in self.box_edges:
                cv2.line(vis, tuple(pts[i]), tuple(pts[j]), (0, 255, 0), 2)

        # Overlay info text
        h = vis.shape[0]
        faces_str = ",".join(sorted(result["visible_faces"])) if result["visible_faces"] else "none"
        total = len(self.valid_ids)
        n = result["n_tags"]
        err = result["reproj_error"]
        lines = [
            f"Tags: {n}/{total}  Faces: {faces_str}",
            f"Reproj: {err:.2f}px" if result["success"] else "No pose",
        ]
        if result["success"]:
            t = result["tvec"].flatten()
            lines.append(f"T: [{t[0]:.1f}, {t[1]:.1f}, {t[2]:.1f}] mm")
        for i, line in enumerate(lines):
            y = h - 10 - (len(lines) - 1 - i) * 25
            cv2.putText(vis, line, (10, y), cv2.FONT_HERSHEY_SIMPLEX,
                        0.6, (0, 255, 0), 2)

        return vis


# ---------------------------------------------------------------------------
# Camera intrinsics
# ---------------------------------------------------------------------------
def load_camera_params(args, frame_shape: tuple[int, ...]
                       ) -> tuple[np.ndarray, np.ndarray]:
    """Load camera matrix and distortion coefficients."""
    if args.calib:
        with open(args.calib) as f:
            data = json.load(f)
        camera_matrix = np.array(data["camera_matrix"], dtype=np.float64)
        dist_coeffs = np.array(data.get("dist_coeffs", [0, 0, 0, 0, 0]), dtype=np.float64)
        return camera_matrix, dist_coeffs

    h, w = frame_shape[:2]
    if args.fx is not None:
        fx = args.fx
        fy = args.fy if args.fy is not None else args.fx
        cx = args.cx if args.cx is not None else w / 2
        cy = args.cy if args.cy is not None else h / 2
    else:
        # Rough default: assume FOV ~60deg -> fx ~ w
        fx = fy = float(w)
        cx, cy = w / 2, h / 2
        print("Warning: no calibration provided, using default intrinsics "
              f"(fx=fy={fx:.0f}, cx={cx:.0f}, cy={cy:.0f})", file=sys.stderr)

    camera_matrix = np.array([
        [fx, 0, cx],
        [0, fy, cy],
        [0, 0, 1],
    ], dtype=np.float64)
    dist_coeffs = np.zeros(5, dtype=np.float64)
    return camera_matrix, dist_coeffs


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(
        description="Detect ArUco/AprilTag cube and estimate 6-DOF pose.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="Examples:\n"
        "  %(prog)s --cube my_cube/config.json\n"
        "  %(prog)s --cube my_cube/config.json --camera 1\n"
        "  %(prog)s --cube my_cube/config.json --image photo.jpg --viz\n"
        "  %(prog)s --cube my_cube/config.json --calib calib.json --viz\n",
    )

    # Cube config
    parser.add_argument("--cube", type=str, required=True,
                        help="Path to config.json from generate_cube.py")

    # Input source (optional — defaults to webcam 0)
    input_grp = parser.add_mutually_exclusive_group()
    input_grp.add_argument("--camera", type=int, default=None, help="Camera index (default: 0)")
    input_grp.add_argument("--image", type=str, default=None, help="Image file path")
    input_grp.add_argument("--video", type=str, default=None, help="Video file path")

    # Camera intrinsics
    parser.add_argument("--calib", type=str, default=None, help="Calibration JSON file")
    parser.add_argument("--fx", type=float, default=None, help="Focal length X (pixels)")
    parser.add_argument("--fy", type=float, default=None, help="Focal length Y (pixels)")
    parser.add_argument("--cx", type=float, default=None, help="Principal point X")
    parser.add_argument("--cy", type=float, default=None, help="Principal point Y")

    # Options
    parser.add_argument("--no-filter", action="store_true", help="Disable temporal smoothing")
    parser.add_argument("--viz", action="store_true", help="Show debug visualization window")

    args = parser.parse_args()

    # Load cube config from JSON
    config, face_id_sets = load_cube_config(args.cube)
    bx, by, bz = config.box_dims
    print(f"Cube: {bx:.4g} x {by:.4g} x {bz:.4g} mm, "
          f"{len(config.tag_ids)} tags ({config.dict_name}), "
          f"cell={config.cell_size:.4g}mm")

    # Determine input source — default to webcam 0
    is_stream = args.image is None
    if args.image is not None:
        frame = cv2.imread(args.image)
        if frame is None:
            print(f"Error: cannot read {args.image}", file=sys.stderr)
            sys.exit(1)
        cap = None
    else:
        if args.video is not None:
            source = args.video
        else:
            source = args.camera if args.camera is not None else 0
        cap = cv2.VideoCapture(source)
        if not cap.isOpened():
            print(f"Error: cannot open camera/video {source}", file=sys.stderr)
            sys.exit(1)
        ret, frame = cap.read()
        if not ret:
            print("Error: cannot read first frame", file=sys.stderr)
            sys.exit(1)
        src_label = f"camera {source}" if args.video is None else args.video
        print(f"Input: {src_label} ({frame.shape[1]}x{frame.shape[0]})")

    # Load camera intrinsics
    camera_matrix, dist_coeffs = load_camera_params(args, frame.shape)
    print(f"Camera: fx={camera_matrix[0,0]:.1f} fy={camera_matrix[1,1]:.1f} "
          f"cx={camera_matrix[0,2]:.1f} cy={camera_matrix[1,2]:.1f}")

    # Create estimator
    enable_filter = not args.no_filter and is_stream
    estimator = CubePoseEstimator(config, face_id_sets, camera_matrix, dist_coeffs, enable_filter)

    # --- Single image mode ---
    if cap is None:
        result = estimator.process_frame(frame)
        if result["success"]:
            r = result["rvec"].flatten()
            t = result["tvec"].flatten()
            print(f"Pose: rvec=[{r[0]:.4f}, {r[1]:.4f}, {r[2]:.4f}] "
                  f"tvec=[{t[0]:.1f}, {t[1]:.1f}, {t[2]:.1f}] mm")
            print(f"  reproj={result['reproj_error']:.2f}px, "
                  f"tags={result['n_tags']}/{len(config.tag_ids)}, "
                  f"faces={','.join(sorted(result['visible_faces']))}")
        else:
            print("No pose detected.")

        if args.viz:
            vis = estimator.draw_result(frame, result)
            cv2.imshow("detect_cube", vis)
            print("Press any key to exit.")
            cv2.waitKey(0)
            cv2.destroyAllWindows()
        return

    # --- Video / camera loop ---
    fps_timer = time.time()
    fps_count = 0
    fps_display = 0.0

    while True:
        if frame is None:
            ret, frame = cap.read()
            if not ret:
                break

        result = estimator.process_frame(frame)

        # FPS counter
        fps_count += 1
        elapsed = time.time() - fps_timer
        if elapsed >= 1.0:
            fps_display = fps_count / elapsed
            fps_count = 0
            fps_timer = time.time()

        if result["success"]:
            r = result["rvec"].flatten()
            t = result["tvec"].flatten()
            faces = ",".join(sorted(result["visible_faces"]))
            print(f"\rrvec=[{r[0]:+.3f},{r[1]:+.3f},{r[2]:+.3f}] "
                  f"tvec=[{t[0]:+.0f},{t[1]:+.0f},{t[2]:+.0f}]mm "
                  f"err={result['reproj_error']:.1f}px "
                  f"tags={result['n_tags']} faces={faces} "
                  f"fps={fps_display:.0f}",
                  end="", flush=True)

        if args.viz:
            vis = estimator.draw_result(frame, result)
            cv2.putText(vis, f"FPS: {fps_display:.0f}", (10, 30),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
            cv2.imshow("detect_cube", vis)
            key = cv2.waitKey(1) & 0xFF
            if key == 27 or key == ord("q"):
                break

        frame = None  # read next frame on next iteration

    print()
    cap.release()
    if args.viz:
        cv2.destroyAllWindows()


if __name__ == "__main__":
    main()
