#!/usr/bin/env python3
"""6-DOF pose detection for ArUco/AprilTag cubes generated by generate_cube.py.

Loads cube geometry from config.json (produced by generate_cube.py),
detects markers in camera/image/video, and estimates the cube's 6-DOF pose.
"""

import argparse
import json
import sys
import threading
import time
from collections import deque
from dataclasses import dataclass, field
from typing import NamedTuple

import cv2
import numpy as np

from aprilcube.generate import CubeConfig, DICT_MAP, FACE_DEFS


# ---------------------------------------------------------------------------
# Load cube config from JSON
# ---------------------------------------------------------------------------
def load_cube_config(path: str) -> tuple[CubeConfig, dict[str, set[int]]]:
    """Load CubeConfig and face→tag mapping from config.json."""
    with open(path) as f:
        data = json.load(f)

    from aprilcube.generate import parse_grid
    gx, gy, gz = parse_grid(data["grid"])
    dict_id = DICT_MAP[data["dict"]]

    config = CubeConfig(
        grid_x=gx, grid_y=gy, grid_z=gz,
        dict_id=dict_id, dict_name=data["dict"],
        tag_ids=data["tag_ids"],
        tag_size_mm=data["tag_size_mm"],
        margin_cells=data["margin_cells"],
        border_cells=data["border_cells"],
        cell_size_mm=data["cell_size_mm"],
    )
    config.compute()

    face_id_sets = {name: set(ids) for name, ids in data["faces"].items()}
    return config, face_id_sets


# ---------------------------------------------------------------------------
# 3D model: tag_id → corner positions on cube surface
# ---------------------------------------------------------------------------
def build_tag_corner_map(config: CubeConfig) -> dict[int, np.ndarray]:
    """Build mapping from tag_id to 3D corner positions (4x3, mm).

    Corners are ordered [TL, TR, BR, BL] as seen from outside the face,
    matching cv2.aruco.detectMarkers() corner ordering.
    """
    tag_corner_map: dict[int, np.ndarray] = {}
    id_cursor = 0
    mp = config.marker_pixels
    cs = config.cell_size

    for face_def in FACE_DEFS:
        _name, normal_ax, normal_sign, right_ax, right_sign, down_ax, down_sign = face_def
        face_rows, face_cols, down_cells, right_cells = config.face_layout(face_def)
        n_tags = face_rows * face_cols

        # Centering offsets (same logic as build_face_grid in generate_cube.py)
        tag_block_w = face_cols * mp + max(0, face_cols - 1) * config.margin_cells
        tag_block_h = face_rows * mp + max(0, face_rows - 1) * config.margin_cells
        row_off = (down_cells - tag_block_h) // 2
        col_off = (right_cells - tag_block_w) // 2

        right_half = config.box_dims[right_ax] / 2.0
        down_half = config.box_dims[down_ax] / 2.0
        face_pos = normal_sign * config.box_dims[normal_ax] / 2.0

        def cell_to_3d(row: float, col: float) -> np.ndarray:
            u = right_sign * (-right_half + col * cs)
            v = down_sign * (-down_half + row * cs)
            pt = np.zeros(3)
            pt[normal_ax] = face_pos
            pt[right_ax] = u
            pt[down_ax] = v
            return pt

        for r in range(face_rows):
            for c in range(face_cols):
                idx = r * face_cols + c
                if id_cursor + idx >= len(config.tag_ids):
                    break
                tag_id = config.tag_ids[id_cursor + idx]

                rs = row_off + r * (mp + config.margin_cells)
                cc = col_off + c * (mp + config.margin_cells)

                # [TL, TR, BR, BL] as seen from outside.
                # Tag patterns are np.fliplr'd in generate_cube.py, so the
                # detector's TL/TR are column-swapped relative to grid coords.
                corners_3d = np.array([
                    cell_to_3d(rs, cc + mp),       # TL
                    cell_to_3d(rs, cc),             # TR
                    cell_to_3d(rs + mp, cc),        # BR
                    cell_to_3d(rs + mp, cc + mp),   # BL
                ], dtype=np.float64)

                tag_corner_map[tag_id] = corners_3d

        id_cursor += n_tags

    return tag_corner_map




# ---------------------------------------------------------------------------
# ArUco detector with tuned parameters
# ---------------------------------------------------------------------------
def create_detector(dict_id: int, fast: bool = False) -> cv2.aruco.ArucoDetector:
    """Create an ArUco detector tuned for 3D-printed markers.

    Args:
        dict_id: ArUco dictionary ID.
        fast: If True, use faster parameters better suited for real-time webcam use.
    """
    dictionary = cv2.aruco.getPredefinedDictionary(dict_id)
    params = cv2.aruco.DetectorParameters()

    if fast:
        # Skip subpix refinement for speed
        params.cornerRefinementMethod = cv2.aruco.CORNER_REFINE_NONE

        # Fewer threshold passes
        params.adaptiveThreshWinSizeMin = 5
        params.adaptiveThreshWinSizeMax = 41
        params.adaptiveThreshWinSizeStep = 12

        # Tighter candidate filtering — reject tiny/huge quads early
        params.minMarkerPerimeterRate = 0.03
        params.maxMarkerPerimeterRate = 4.0
        params.polygonalApproxAccuracyRate = 0.05
        params.minCornerDistanceRate = 0.05
        params.minDistanceToBorder = 2

        params.perspectiveRemovePixelPerCell = 6
        params.perspectiveRemoveIgnoredMarginPerCell = 0.13
        params.errorCorrectionRate = 0.6
    else:
        # Sub-pixel corner refinement — critical for PnP accuracy
        params.cornerRefinementMethod = cv2.aruco.CORNER_REFINE_SUBPIX
        params.cornerRefinementWinSize = 5
        params.cornerRefinementMaxIterations = 50
        params.cornerRefinementMinAccuracy = 0.01

        # Adaptive thresholding — wider range for 3D-printed surface texture
        params.adaptiveThreshWinSizeMin = 3
        params.adaptiveThreshWinSizeMax = 53
        params.adaptiveThreshWinSizeStep = 4

        # Candidate filtering — relax for oblique views
        params.minMarkerPerimeterRate = 0.01
        params.maxMarkerPerimeterRate = 4.0
        params.polygonalApproxAccuracyRate = 0.05
        params.minCornerDistanceRate = 0.02
        params.minDistanceToBorder = 1

        # Bit decoding — higher sampling for oblique perspectives
        params.perspectiveRemovePixelPerCell = 8
        params.perspectiveRemoveIgnoredMarginPerCell = 0.13
        params.errorCorrectionRate = 0.6

    return cv2.aruco.ArucoDetector(dictionary, params)


def create_fallback_detector(dict_id: int) -> cv2.aruco.ArucoDetector:
    """Create a relaxed detector for motion-blurred frames.

    Uses wider thresholding, higher error correction, and looser candidate
    filtering to recover markers that the primary detector misses.
    """
    dictionary = cv2.aruco.getPredefinedDictionary(dict_id)
    params = cv2.aruco.DetectorParameters()

    params.cornerRefinementMethod = cv2.aruco.CORNER_REFINE_NONE

    # Wider adaptive threshold range with finer steps
    params.adaptiveThreshWinSizeMin = 3
    params.adaptiveThreshWinSizeMax = 63
    params.adaptiveThreshWinSizeStep = 6

    # Very relaxed candidate filtering — blurred quads are rounder
    params.minMarkerPerimeterRate = 0.01
    params.maxMarkerPerimeterRate = 4.0
    params.polygonalApproxAccuracyRate = 0.08
    params.minCornerDistanceRate = 0.02
    params.minDistanceToBorder = 1

    # Higher error correction to tolerate bit corruption from blur
    params.perspectiveRemovePixelPerCell = 8
    params.perspectiveRemoveIgnoredMarginPerCell = 0.2
    params.errorCorrectionRate = 1.0

    # Lower thresholds for edge detection on soft images
    params.minMarkerDistanceRate = 0.01

    return cv2.aruco.ArucoDetector(dictionary, params)


def _sharpen(gray: np.ndarray) -> np.ndarray:
    """Lightweight unsharp mask to recover edges from motion blur."""
    blurred = cv2.GaussianBlur(gray, (0, 0), sigmaX=2.0)
    return cv2.addWeighted(gray, 1.5, blurred, -0.5, 0)


_clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))


def _preprocess(gray: np.ndarray) -> np.ndarray:
    """CLAHE contrast normalization for robust marker detection."""
    return _clahe.apply(gray)


def _quad_quality(corners: np.ndarray, min_area: float = 100.0) -> float:
    """Score a detected quad's geometric quality in [0, 1].

    Checks area, convexity, and aspect ratio.  Returns 0.0 for degenerate
    quads (too small, non-convex, extreme aspect ratio).
    """
    # corners: (4, 2)
    area = cv2.contourArea(corners.astype(np.float32))
    if area < min_area:
        return 0.0

    # Must be convex
    if not cv2.isContourConvex(corners.astype(np.float32)):
        return 0.0

    # Side lengths
    sides = np.array([
        np.linalg.norm(corners[(i + 1) % 4] - corners[i]) for i in range(4)
    ])
    if sides.min() < 1e-3:
        return 0.0

    # Aspect ratio: ratio of shortest to longest side (1.0 = square)
    aspect = sides.min() / sides.max()
    if aspect < 0.15:          # very skewed quad — likely noise
        return 0.0

    # Score: blend of area confidence and aspect ratio
    area_score = min(area / 400.0, 1.0)   # ramp up to 1.0 at 400 px²
    return float(aspect * 0.5 + area_score * 0.5)


# ---------------------------------------------------------------------------
# Pose estimation
# ---------------------------------------------------------------------------
def estimate_pose(
    object_points: np.ndarray,
    image_points: np.ndarray,
    camera_matrix: np.ndarray,
    dist_coeffs: np.ndarray,
    prev_rvec: np.ndarray | None = None,
    prev_tvec: np.ndarray | None = None,
) -> tuple[bool, np.ndarray | None, np.ndarray | None, float, np.ndarray | None]:
    """Estimate 6-DOF pose from 2D-3D correspondences.

    Returns (success, rvec, tvec, reproj_error, inliers).
    """
    n_points = object_points.shape[0]
    if n_points < 4:
        return False, None, None, float("inf"), None

    use_guess = prev_rvec is not None and prev_tvec is not None

    # ITERATIVE with prior disambiguates coplanar (single-tag) cases;
    # SQPNP is globally optimal for cold starts (no local-minimum risk).
    pnp_flag = cv2.SOLVEPNP_ITERATIVE if use_guess else cv2.SOLVEPNP_SQPNP

    if n_points >= 6:
        try:
            success, rvec, tvec, inliers = cv2.solvePnPRansac(
                objectPoints=object_points,
                imagePoints=image_points,
                cameraMatrix=camera_matrix,
                distCoeffs=dist_coeffs,
                rvec=prev_rvec.copy() if use_guess else None,
                tvec=prev_tvec.copy() if use_guess else None,
                useExtrinsicGuess=use_guess,
                iterationsCount=200,
                reprojectionError=3.0,
                confidence=0.99,
                flags=pnp_flag,
            )
        except cv2.error:
            success, rvec, tvec, inliers = cv2.solvePnPRansac(
                objectPoints=object_points,
                imagePoints=image_points,
                cameraMatrix=camera_matrix,
                distCoeffs=dist_coeffs,
                rvec=prev_rvec.copy() if use_guess else None,
                tvec=prev_tvec.copy() if use_guess else None,
                useExtrinsicGuess=use_guess,
                iterationsCount=200,
                reprojectionError=3.0,
                confidence=0.99,
                flags=cv2.SOLVEPNP_ITERATIVE,
            )
    else:
        try:
            success, rvec, tvec = cv2.solvePnP(
                objectPoints=object_points,
                imagePoints=image_points,
                cameraMatrix=camera_matrix,
                distCoeffs=dist_coeffs,
                rvec=prev_rvec.copy() if use_guess else None,
                tvec=prev_tvec.copy() if use_guess else None,
                useExtrinsicGuess=use_guess,
                flags=pnp_flag,
            )
        except cv2.error:
            success, rvec, tvec = cv2.solvePnP(
                objectPoints=object_points,
                imagePoints=image_points,
                cameraMatrix=camera_matrix,
                distCoeffs=dist_coeffs,
                rvec=prev_rvec.copy() if use_guess else None,
                tvec=prev_tvec.copy() if use_guess else None,
                useExtrinsicGuess=use_guess,
                flags=cv2.SOLVEPNP_ITERATIVE,
            )
        inliers = np.arange(n_points).reshape(-1, 1) if success else None

    if not success:
        return False, None, None, float("inf"), None

    # Refine with Levenberg-Marquardt on inliers
    if inliers is not None and len(inliers) >= 4:
        idx = inliers.flatten()
        rvec, tvec = cv2.solvePnPRefineLM(
            objectPoints=object_points[idx],
            imagePoints=image_points[idx],
            cameraMatrix=camera_matrix,
            distCoeffs=dist_coeffs,
            rvec=rvec,
            tvec=tvec,
        )

    # Reprojection error
    projected, _ = cv2.projectPoints(object_points, rvec, tvec, camera_matrix, dist_coeffs)
    projected = projected.reshape(-1, 2)
    reproj_err = float(np.mean(np.linalg.norm(image_points - projected, axis=1)))

    return success, rvec, tvec, reproj_err, inliers


# ---------------------------------------------------------------------------
# Temporal filter
# ---------------------------------------------------------------------------
class PoseFilter:
    """EMA filter for smoothing pose in video."""

    def __init__(self, alpha: float = 0.3, max_jump_mm: float = 50.0,
                 max_jump_deg: float = 30.0):
        self.alpha = alpha
        self.max_jump_mm = max_jump_mm
        self.max_jump_deg = max_jump_deg
        self.rvec: np.ndarray | None = None
        self.tvec: np.ndarray | None = None

    def update(self, rvec: np.ndarray, tvec: np.ndarray
               ) -> tuple[np.ndarray, np.ndarray]:
        if self.rvec is None:
            self.rvec = rvec.copy()
            self.tvec = tvec.copy()
            return self.rvec.copy(), self.tvec.copy()

        dt = float(np.linalg.norm(tvec - self.tvec))
        R_prev, _ = cv2.Rodrigues(self.rvec)
        R_curr, _ = cv2.Rodrigues(rvec)
        R_diff = R_curr @ R_prev.T
        angle = np.arccos(np.clip((np.trace(R_diff) - 1) / 2, -1, 1))
        angle_deg = float(np.degrees(angle))

        if dt > self.max_jump_mm or angle_deg > self.max_jump_deg:
            self.rvec = rvec.copy()
            self.tvec = tvec.copy()
        else:
            self.tvec = self.alpha * tvec + (1 - self.alpha) * self.tvec
            # SLERP-style rotation interpolation (linear EMA on Rodrigues
            # vectors is wrong — axis direction and angle don't blend linearly).
            # R_filtered = R_prev @ expm(alpha * logm(R_prev^T @ R_curr))
            R_delta = R_prev.T @ R_curr
            delta_rvec, _ = cv2.Rodrigues(R_delta)
            scaled_delta, _ = cv2.Rodrigues(self.alpha * delta_rvec)
            R_filtered = R_prev @ scaled_delta
            self.rvec, _ = cv2.Rodrigues(R_filtered)

        return self.rvec.copy(), self.tvec.copy()

    def reset(self):
        self.rvec = None
        self.tvec = None


# ---------------------------------------------------------------------------
# Quaternion utilities (Hamilton convention: q = [w, x, y, z])
# ---------------------------------------------------------------------------
def _rvec_to_quat(rvec: np.ndarray) -> np.ndarray:
    """Rodrigues (3,) or (3,1) → unit quaternion [w, x, y, z], always w >= 0."""
    r = rvec.flatten()
    angle = float(np.linalg.norm(r))
    if angle < 1e-10:
        return np.array([1.0, 0.0, 0.0, 0.0])
    axis = r / angle
    ha = angle / 2
    sa = np.sin(ha)
    q = np.array([np.cos(ha), sa * axis[0], sa * axis[1], sa * axis[2]])
    # Canonicalize to w >= 0 hemisphere (q and -q are the same rotation)
    if q[0] < 0:
        q = -q
    return q


def _quat_to_rvec(q: np.ndarray) -> np.ndarray:
    """Unit quaternion [w, x, y, z] → Rodrigues (3, 1), angle in [0, π]."""
    # Canonicalize to w >= 0
    if q[0] < 0:
        q = -q
    w, x, y, z = q
    sin_ha = np.sqrt(x * x + y * y + z * z)
    if sin_ha < 1e-10:
        return np.zeros((3, 1))
    angle = 2.0 * np.arctan2(sin_ha, w)
    axis = np.array([x, y, z]) / sin_ha
    return (angle * axis).reshape(3, 1)


def _quat_mul(q1: np.ndarray, q2: np.ndarray) -> np.ndarray:
    """Hamilton product q1 * q2."""
    w1, x1, y1, z1 = q1
    w2, x2, y2, z2 = q2
    return np.array([
        w1 * w2 - x1 * x2 - y1 * y2 - z1 * z2,
        w1 * x2 + x1 * w2 + y1 * z2 - z1 * y2,
        w1 * y2 - x1 * z2 + y1 * w2 + z1 * x2,
        w1 * z2 + x1 * y2 - y1 * x2 + z1 * w2,
    ])


def _quat_conj(q: np.ndarray) -> np.ndarray:
    return np.array([q[0], -q[1], -q[2], -q[3]])


def _quat_to_rotvec(q: np.ndarray) -> np.ndarray:
    """Quaternion → rotation vector (3,). Handles small angles."""
    # Canonicalize to w >= 0 (same rotation, avoids sign discontinuity)
    if q[0] < 0:
        q = -q
    w, x, y, z = q
    sin_ha = np.sqrt(x * x + y * y + z * z)
    if sin_ha < 1e-10:
        return 2.0 * np.array([x, y, z])
    angle = 2.0 * np.arctan2(sin_ha, w)
    return angle * np.array([x, y, z]) / sin_ha


# ---------------------------------------------------------------------------
# Kalman pose filter
# ---------------------------------------------------------------------------
class PoseSnapshot(NamedTuple):
    """Immutable record of one filter output."""
    timestamp: float
    rvec: np.ndarray
    tvec: np.ndarray
    velocity: np.ndarray      # (3,) mm/s
    omega: np.ndarray          # (3,) rad/s
    measurement_used: bool
    reproj_error: float
    n_tags: int


@dataclass
class KalmanFilterConfig:
    """Tuning knobs for KalmanPoseFilter."""
    # Process noise (constant-velocity model) — adaptive range
    sigma_accel_low: float = 100.0   # mm/s², when stationary
    sigma_accel_high: float = 2000.0 # mm/s², when moving fast
    sigma_alpha_low: float = 2.0     # rad/s², when stationary
    sigma_alpha_high: float = 30.0   # rad/s², when moving fast

    # Velocity thresholds for interpolating process noise
    vel_low: float = 5.0             # mm/s — below this, use _low noise
    vel_high: float = 200.0          # mm/s — above this, use _high noise
    omega_low: float = 0.1           # rad/s
    omega_high: float = 3.0          # rad/s

    # Base measurement noise (scaled adaptively per frame)
    base_sigma_t: float = 3.0        # mm
    base_sigma_r: float = 0.02       # rad

    # Innovation gating (Mahalanobis distance thresholds)
    mahal_gate: float = 16.0         # soft reject above this
    mahal_hard_reset: float = 100.0  # hard re-init above this
    max_outliers_before_reset: int = 3

    # Initialization covariance
    init_sigma_pos: float = 20.0     # mm
    init_sigma_vel: float = 100.0    # mm/s
    init_sigma_rot: float = 0.2      # rad
    init_sigma_omega: float = 2.0    # rad/s

    # Limits
    max_predict_dt: float = 0.1      # seconds — coast on velocity before reset

    # History buffer
    history_size: int = 300          # ~10 s at 30 fps


class KalmanPoseFilter:
    """Error-state Kalman filter for 6-DOF pose tracking.

    Translation: standard linear KF, state = [x, y, z, vx, vy, vz].
    Rotation:    multiplicative error-state KF on unit quaternion,
                 error state = [dθx, dθy, dθz, ωx, ωy, ωz].

    The nominal quaternion is maintained separately and updated
    multiplicatively after each correction step.
    """

    def __init__(self, config: KalmanFilterConfig | None = None):
        self.cfg = config or KalmanFilterConfig()
        self._initialized = False

        # Translation KF: [px, py, pz, vx, vy, vz]
        self._x_t = np.zeros(6)
        self._P_t = np.eye(6)

        # Rotation error-state KF: [dθx, dθy, dθz, ωx, ωy, ωz]
        self._q = np.array([1.0, 0.0, 0.0, 0.0])  # nominal quaternion
        self._x_r = np.zeros(6)
        self._P_r = np.eye(6)

        # Shared measurement matrix H = [I_3 | 0_3]
        self._H = np.zeros((3, 6))
        self._H[:3, :3] = np.eye(3)

        self._last_ts: float = 0.0
        self._outlier_count = 0
        self._history: deque[PoseSnapshot] = deque(maxlen=self.cfg.history_size)

    # -- public interface ---------------------------------------------------

    def update(
        self,
        rvec: np.ndarray,
        tvec: np.ndarray,
        timestamp: float,
        reproj_error: float = 1.0,
        n_tags: int = 1,
        n_inliers: int = 4,
    ) -> tuple[np.ndarray, np.ndarray]:
        """Incorporate a PnP measurement. Returns (filtered_rvec, filtered_tvec)."""
        if not self._initialized:
            self._init_state(rvec, tvec, timestamp)
            self._snap(timestamp, True, reproj_error, n_tags)
            return self._output()

        dt = timestamp - self._last_ts
        if dt <= 0:
            dt = 1.0 / 30.0
        if dt > self.cfg.max_predict_dt:
            self._init_state(rvec, tvec, timestamp)
            self._snap(timestamp, True, reproj_error, n_tags)
            return self._output()

        # 1) predict
        self._predict(dt)
        self._last_ts = timestamp

        # 2) adaptive measurement noise
        R_t, R_r = self._adaptive_R(reproj_error, n_tags, n_inliers)

        # 3) translation innovation
        z_t = tvec.flatten()
        H = self._H
        innov_t = z_t - H @ self._x_t
        S_t = H @ self._P_t @ H.T + R_t
        mahal_t = float(innov_t @ np.linalg.solve(S_t, innov_t))

        # 4) rotation innovation (error-state)
        q_meas = _rvec_to_quat(rvec)
        if np.dot(self._q, q_meas) < 0:
            q_meas = -q_meas
        dq = _quat_mul(_quat_conj(self._q), q_meas)
        innov_r = _quat_to_rotvec(dq)
        S_r = H @ self._P_r @ H.T + R_r
        mahal_r = float(innov_r @ np.linalg.solve(S_r, innov_r))

        mahal = mahal_t + mahal_r

        # 5) gating
        if mahal > self.cfg.mahal_hard_reset or \
                self._outlier_count >= self.cfg.max_outliers_before_reset:
            self._init_state(rvec, tvec, timestamp)
            self._snap(timestamp, True, reproj_error, n_tags)
            return self._output()
        if mahal > self.cfg.mahal_gate:
            R_t = R_t * 10.0
            R_r = R_r * 10.0
            S_t = H @ self._P_t @ H.T + R_t
            S_r = H @ self._P_r @ H.T + R_r
            self._outlier_count += 1
        else:
            self._outlier_count = 0

        # 6) Kalman update — translation (Joseph form)
        K_t = self._P_t @ H.T @ np.linalg.inv(S_t)
        self._x_t += K_t @ innov_t
        I_KH = np.eye(6) - K_t @ H
        self._P_t = I_KH @ self._P_t @ I_KH.T + K_t @ R_t @ K_t.T

        # 7) Kalman update — rotation error-state (Joseph form)
        K_r = self._P_r @ H.T @ np.linalg.inv(S_r)
        self._x_r += K_r @ innov_r
        I_KH_r = np.eye(6) - K_r @ H
        self._P_r = I_KH_r @ self._P_r @ I_KH_r.T + K_r @ R_r @ K_r.T

        # 8) fold error rotation into nominal quaternion, reset error
        dq_corr = _rvec_to_quat(self._x_r[:3])
        self._q = _quat_mul(self._q, dq_corr)
        self._q /= np.linalg.norm(self._q)
        self._x_r[:3] = 0.0

        # symmetry guard
        self._P_t = (self._P_t + self._P_t.T) / 2
        self._P_r = (self._P_r + self._P_r.T) / 2

        self._snap(timestamp, True, reproj_error, n_tags)
        return self._output()

    def predict(self, timestamp: float) -> tuple[np.ndarray, np.ndarray] | None:
        """Predict pose at *timestamp* without a measurement.

        Returns (rvec, tvec) or None if not initialized / dt too large.
        """
        if not self._initialized:
            return None
        dt = timestamp - self._last_ts
        if dt < 0 or dt > self.cfg.max_predict_dt:
            return None

        # translate
        F = np.eye(6)
        F[0, 3] = F[1, 4] = F[2, 5] = dt
        x_t_pred = F @ self._x_t
        tvec = x_t_pred[:3].reshape(3, 1)

        # rotate
        omega = self._x_r[3:6]
        angle = float(np.linalg.norm(omega)) * dt
        if angle > 1e-10:
            axis = omega / np.linalg.norm(omega)
            sa = np.sin(angle / 2)
            dq = np.array([np.cos(angle / 2), sa * axis[0], sa * axis[1], sa * axis[2]])
            q_pred = _quat_mul(self._q, dq)
            q_pred /= np.linalg.norm(q_pred)
        else:
            q_pred = self._q.copy()
        rvec = _quat_to_rvec(q_pred)

        return rvec, tvec

    def get_velocity(self) -> tuple[np.ndarray, np.ndarray] | None:
        """Return (linear_vel mm/s, angular_vel rad/s) or None."""
        if not self._initialized:
            return None
        return self._x_t[3:6].copy(), self._x_r[3:6].copy()

    def reset(self):
        self._initialized = False
        self._x_t[:] = 0
        self._P_t = np.eye(6)
        self._q = np.array([1.0, 0.0, 0.0, 0.0])
        self._x_r[:] = 0
        self._P_r = np.eye(6)
        self._outlier_count = 0

    @property
    def is_initialized(self) -> bool:
        return self._initialized

    @property
    def history(self) -> deque[PoseSnapshot]:
        return self._history

    # -- internals ----------------------------------------------------------

    def _init_state(self, rvec: np.ndarray, tvec: np.ndarray, ts: float):
        self._x_t[:3] = tvec.flatten()
        self._x_t[3:] = 0.0
        self._q = _rvec_to_quat(rvec)
        self._x_r[:] = 0.0

        c = self.cfg
        self._P_t = np.diag([
            c.init_sigma_pos ** 2, c.init_sigma_pos ** 2, c.init_sigma_pos ** 2,
            c.init_sigma_vel ** 2, c.init_sigma_vel ** 2, c.init_sigma_vel ** 2,
        ])
        self._P_r = np.diag([
            c.init_sigma_rot ** 2, c.init_sigma_rot ** 2, c.init_sigma_rot ** 2,
            c.init_sigma_omega ** 2, c.init_sigma_omega ** 2, c.init_sigma_omega ** 2,
        ])
        self._last_ts = ts
        self._initialized = True
        self._outlier_count = 0

    @staticmethod
    def _lerp_clamp(val: float, lo: float, hi: float) -> float:
        """Map val from [lo, hi] to [0, 1], clamped."""
        if hi <= lo:
            return 0.0
        return max(0.0, min(1.0, (val - lo) / (hi - lo)))

    def _adaptive_process_noise(self) -> tuple[float, float]:
        """Return (sigma_accel, sigma_alpha) scaled by current velocity."""
        c = self.cfg
        speed = float(np.linalg.norm(self._x_t[3:6]))
        omega_speed = float(np.linalg.norm(self._x_r[3:6]))

        t_frac = self._lerp_clamp(speed, c.vel_low, c.vel_high)
        r_frac = self._lerp_clamp(omega_speed, c.omega_low, c.omega_high)

        sigma_a = c.sigma_accel_low + t_frac * (c.sigma_accel_high - c.sigma_accel_low)
        sigma_r = c.sigma_alpha_low + r_frac * (c.sigma_alpha_high - c.sigma_alpha_low)
        return sigma_a, sigma_r

    def _predict(self, dt: float):
        sigma_accel, sigma_alpha = self._adaptive_process_noise()

        # translation
        F = np.eye(6)
        F[0, 3] = F[1, 4] = F[2, 5] = dt
        self._x_t = F @ self._x_t
        self._P_t = F @ self._P_t @ F.T + self._build_Q(dt, sigma_accel)

        # rotate nominal quaternion by angular velocity
        omega = self._x_r[3:6]
        angle = float(np.linalg.norm(omega)) * dt
        if angle > 1e-10:
            axis = omega / np.linalg.norm(omega)
            sa = np.sin(angle / 2)
            dq = np.array([np.cos(angle / 2), sa * axis[0], sa * axis[1], sa * axis[2]])
            self._q = _quat_mul(self._q, dq)
            self._q /= np.linalg.norm(self._q)

        # rotation error-state
        F_r = np.eye(6)
        F_r[0, 3] = F_r[1, 4] = F_r[2, 5] = dt
        self._x_r = F_r @ self._x_r
        self._x_r[:3] = 0.0  # error always reset
        self._P_r = F_r @ self._P_r @ F_r.T + self._build_Q(dt, sigma_alpha)

    @staticmethod
    def _build_Q(dt: float, sigma: float) -> np.ndarray:
        s2 = sigma * sigma
        dt2 = dt * dt
        dt3 = dt2 * dt
        dt4 = dt3 * dt
        Q = np.zeros((6, 6))
        for i in range(3):
            Q[i, i] = s2 * dt4 / 4
            Q[i, i + 3] = s2 * dt3 / 2
            Q[i + 3, i] = s2 * dt3 / 2
            Q[i + 3, i + 3] = s2 * dt2
        return Q

    def _adaptive_R(self, reproj: float, n_tags: int, n_inliers: int
                    ) -> tuple[np.ndarray, np.ndarray]:
        reproj_factor = max(1.0, reproj ** 2)
        tag_factor = max(1.0, 4.0 / max(n_tags, 1))
        n_pts = n_tags * 4
        inlier_ratio = n_inliers / max(n_pts, 1)
        inlier_factor = max(1.0, 1.0 / max(inlier_ratio, 0.3))

        scale = reproj_factor * tag_factor * inlier_factor

        st = self.cfg.base_sigma_t * scale
        sr = self.cfg.base_sigma_r * scale
        return (st ** 2) * np.eye(3), (sr ** 2) * np.eye(3)

    def _output(self) -> tuple[np.ndarray, np.ndarray]:
        rvec = _quat_to_rvec(self._q)
        tvec = self._x_t[:3].reshape(3, 1)
        return rvec, tvec

    def _snap(self, ts: float, meas: bool, reproj: float, n_tags: int):
        rvec, tvec = self._output()
        self._history.append(PoseSnapshot(
            timestamp=ts,
            rvec=rvec.copy(),
            tvec=tvec.copy(),
            velocity=self._x_t[3:6].copy(),
            omega=self._x_r[3:6].copy(),
            measurement_used=meas,
            reproj_error=reproj,
            n_tags=n_tags,
        ))


# ---------------------------------------------------------------------------
# Main estimator
# ---------------------------------------------------------------------------
class CubePoseEstimator:
    """Detects ArUco tags on a cube and estimates 6-DOF pose."""

    def __init__(self, config: CubeConfig, face_id_sets: dict[str, set[int]],
                 camera_matrix: np.ndarray, dist_coeffs: np.ndarray,
                 enable_filter: bool = True,
                 filter_config: KalmanFilterConfig | None = None,
                 fast: bool = False,
                 extrinsic: np.ndarray | None = None,
                 model_dir: str | None = None):
        self.config = config
        self.camera_matrix = camera_matrix
        self.dist_coeffs = dist_coeffs
        self.extrinsic = np.asarray(extrinsic, dtype=np.float64) if extrinsic is not None else None
        self.model_dir = model_dir

        self.tag_corner_map = build_tag_corner_map(config)
        self.valid_ids = set(self.tag_corner_map.keys())
        self.face_id_sets = face_id_sets
        self.detector = create_detector(config.dict_id, fast=fast)
        self.fallback_detector = create_fallback_detector(config.dict_id)
        self.pose_filter: KalmanPoseFilter | None = (
            KalmanPoseFilter(filter_config) if enable_filter else None
        )

        self.prev_rvec: np.ndarray | None = None
        self.prev_tvec: np.ndarray | None = None

        # Optical flow state: track corners across frames when detection fails
        self._prev_gray: np.ndarray | None = None
        self._prev_corners_2d: np.ndarray | None = None  # (N, 2) float32
        self._prev_corners_3d: np.ndarray | None = None  # (N, 3) float64
        self._flow_lk_params = dict(
            winSize=(31, 31),
            maxLevel=4,
            criteria=(cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 30, 0.01),
        )

        # Box wireframe corners for visualization
        bx, by, bz = config.box_dims
        hx, hy, hz = bx / 2, by / 2, bz / 2
        self.box_corners_3d = np.array([
            [-hx, -hy, -hz], [+hx, -hy, -hz], [+hx, +hy, -hz], [-hx, +hy, -hz],
            [-hx, -hy, +hz], [+hx, -hy, +hz], [+hx, +hy, +hz], [-hx, +hy, +hz],
        ], dtype=np.float64)
        self.box_edges = [
            (0, 1), (1, 2), (2, 3), (3, 0),  # bottom
            (4, 5), (5, 6), (6, 7), (7, 4),  # top
            (0, 4), (1, 5), (2, 6), (3, 7),  # verticals
        ]

        # Latest detection state (read by viser background thread)
        self._latest_result: dict | None = None
        self._latest_frame: np.ndarray | None = None
        self._latest_lock = threading.Lock()
        self._frame_counter = 0
        self._fps = 0.0
        self._fps_t = time.time()
        self._fps_n = 0

        # Viser state (populated by build_viser)
        self._viser_gui_image = None
        self._viser_gui_status = None
        self._viser_server = None
        self._viser_rendered_counter = -1

    def _try_predict(self, timestamp: float, result: dict) -> dict:
        """Try KF prediction as fallback when detection/PnP fails."""
        if self.pose_filter and self.pose_filter.is_initialized:
            pred = self.pose_filter.predict(timestamp)
            if pred is not None:
                rvec, tvec = pred
                result["success"] = True
                result["rvec"] = rvec
                result["tvec"] = tvec
                T = np.eye(4)
                T[:3, :3], _ = cv2.Rodrigues(rvec)
                T[:3, 3] = tvec.flatten()
                result["T"] = T
                result["predicted"] = True
                # Don't update prev_rvec/tvec — keep last measured pose
                # as PnP initial guess to avoid feedback from bad predictions.
                return result
        # prediction unavailable — hard reset
        self.prev_rvec = None
        self.prev_tvec = None
        if self.pose_filter:
            self.pose_filter.reset()
        return result

    def _recover_rejected(
        self,
        detections: list[tuple[int, np.ndarray]],
        seen_ids: set[int],
        rejected_quads: list,
        prior_rvec: np.ndarray,
        prior_tvec: np.ndarray,
        max_corner_dist: float = 15.0,
    ) -> list[tuple[int, np.ndarray]]:
        """Match rejected ArUco candidates against predicted tag positions.

        For each undetected tag, project its 3D corners using the prior pose
        and check if any rejected quad's corners are close. If so, adopt that
        quad's corners as a detection for that tag.
        """
        if not rejected_quads:
            return detections

        # Project all undetected tags
        undetected = [
            tid for tid in self.valid_ids if tid not in seen_ids
        ]
        if not undetected:
            return detections

        # Only consider tags on camera-facing faces
        R_prior, _ = cv2.Rodrigues(prior_rvec)
        candidates = []  # (tag_id, projected_corners_2d (4,2))
        for tid in undetected:
            # Check if this tag's face normal points toward camera
            face_normal = None
            for fd in FACE_DEFS:
                for face_name, id_set in self.face_id_sets.items():
                    if fd[0] == face_name and tid in id_set:
                        n = np.zeros(3)
                        n[fd[1]] = fd[2]
                        face_normal = n
                        break
                if face_normal is not None:
                    break
            if face_normal is not None:
                normal_cam = R_prior @ face_normal
                if normal_cam[2] > 0:  # back-facing
                    continue

            obj_corners = self.tag_corner_map[tid]  # (4, 3)
            proj, _ = cv2.projectPoints(
                obj_corners, prior_rvec, prior_tvec,
                self.camera_matrix, self.dist_coeffs,
            )
            proj_2d = proj.reshape(4, 2)
            # Skip tags projected outside image or behind camera
            if np.any(proj_2d < -50) or np.any(proj_2d > 2000):
                continue
            candidates.append((tid, proj_2d))

        if not candidates:
            return detections

        # Match each rejected quad against candidate projections
        for quad in rejected_quads:
            quad_pts = quad.reshape(4, 2) if quad.shape != (4, 2) else quad
            best_tid = None
            best_dist = max_corner_dist
            for tid, proj_2d in candidates:
                # Mean distance across all 4 corners
                dist = float(np.mean(np.linalg.norm(quad_pts - proj_2d, axis=1)))
                if dist < best_dist:
                    best_dist = dist
                    best_tid = tid

            if best_tid is not None:
                detections.append((best_tid, quad_pts))
                seen_ids.add(best_tid)
                # Remove from candidates so we don't double-match
                candidates = [(t, p) for t, p in candidates if t != best_tid]
                if not candidates:
                    break

        return detections

    def _track_corners_optflow(
        self, gray: np.ndarray,
        predicted_rvec: np.ndarray | None = None,
        predicted_tvec: np.ndarray | None = None,
    ) -> tuple[np.ndarray, np.ndarray] | None:
        """Track previous frame's corners into current frame using optical flow.

        If a predicted pose is available (from KF), projects where corners should
        be in the current frame and uses that as initial guess for LK — this
        allows tracking through large displacements (abrupt motion).

        Returns (object_points, image_points) or None if tracking fails.
        """
        if (self._prev_gray is None or self._prev_corners_2d is None
                or len(self._prev_corners_2d) < 4):
            return None

        prev_pts = self._prev_corners_2d.reshape(-1, 1, 2).astype(np.float32)

        # If we have a KF prediction, project 3D corners to get initial guess
        # for where points moved to. This is critical for large displacements.
        init_guess = None
        if predicted_rvec is not None and predicted_tvec is not None:
            proj, _ = cv2.projectPoints(
                self._prev_corners_3d, predicted_rvec, predicted_tvec,
                self.camera_matrix, self.dist_coeffs,
            )
            init_guess = proj.reshape(-1, 1, 2).astype(np.float32)

        lk_flags = cv2.OPTFLOW_USE_INITIAL_FLOW if init_guess is not None else 0
        lk_params = {**self._flow_lk_params, "flags": lk_flags}

        curr_pts, status, err = cv2.calcOpticalFlowPyrLK(
            self._prev_gray, gray, prev_pts,
            init_guess if init_guess is not None else None,
            **lk_params,
        )

        if curr_pts is None or status is None:
            return None

        # Forward-backward consistency check: track back and verify
        back_pts, back_status, _ = cv2.calcOpticalFlowPyrLK(
            gray, self._prev_gray, curr_pts, None, **self._flow_lk_params,
        )
        if back_pts is None:
            return None

        # Keep only points that survived both passes and are consistent
        fb_dist = np.linalg.norm(
            prev_pts.reshape(-1, 2) - back_pts.reshape(-1, 2), axis=1
        )
        # Relax FB threshold when using predicted hint (motion is large)
        fb_thresh = 4.0 if init_guess is not None else 2.0
        good = (status.flatten() == 1) & (back_status.flatten() == 1) & (fb_dist < fb_thresh)

        if good.sum() < 4:
            return None

        obj_pts = self._prev_corners_3d[good]
        img_pts = curr_pts.reshape(-1, 2)[good]
        return obj_pts.astype(np.float64), img_pts.astype(np.float64)

    def _save_corners_for_flow(
        self, gray: np.ndarray, detections: list[tuple[int, np.ndarray]]
    ):
        """Store current frame's detected corners for next frame's optical flow."""
        if not detections:
            return
        corners_2d = []
        corners_3d = []
        for tag_id, c2d in detections:
            corners_2d.append(c2d)
            corners_3d.append(self.tag_corner_map[tag_id])
        self._prev_gray = gray.copy()
        self._prev_corners_2d = np.vstack(corners_2d).astype(np.float32)
        self._prev_corners_3d = np.vstack(corners_3d).astype(np.float64)

    def _store_latest(self, result: dict, frame: np.ndarray) -> dict:
        """Store the latest result/frame for the viser background thread."""
        result["debug_viz"] = self.draw_result(frame, result)
        with self._latest_lock:
            self._latest_result = result
            self._latest_frame = frame
            self._frame_counter += 1
        # FPS tracking
        self._fps_n += 1
        elapsed = time.time() - self._fps_t
        if elapsed >= 1.0:
            self._fps = self._fps_n / elapsed
            self._fps_n = 0
            self._fps_t = time.time()
        return result

    def process_frame(self, image: np.ndarray,
                      timestamp: float | None = None) -> dict:
        """Process a single frame and return pose result.

        Args:
            image: BGR or grayscale frame.
            timestamp: Monotonic time in seconds for this frame.
                       If None, uses ``time.monotonic()``.
        """
        if timestamp is None:
            timestamp = time.monotonic()

        result = {
            "success": False, "rvec": None, "tvec": None, "T": None,
            "reproj_error": float("inf"), "n_tags": 0,
            "n_inliers": 0, "detections": [], "tag_ids": [],
            "visible_faces": set(), "predicted": False,
        }

        # Detect
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) if len(image.shape) == 3 else image
        enhanced = _preprocess(gray)
        try:
            corners_list, ids, rejected = self.detector.detectMarkers(enhanced)
        except cv2.error:
            corners_list, ids, rejected = (), None, ()

        # Collect valid detections from primary pass
        detections: list[tuple[int, np.ndarray]] = []
        seen_ids: set[int] = set()
        if ids is not None:
            for i in range(len(ids)):
                tag_id = int(ids[i][0])
                if tag_id in self.valid_ids:
                    detections.append((tag_id, corners_list[i].reshape(4, 2)))
                    seen_ids.add(tag_id)

        # Fallback: sharpen + relaxed detector only when primary finds nothing
        fb_rejected: tuple = ()
        if len(detections) == 0 and self.prev_rvec is not None:
            sharp = _sharpen(enhanced)
            try:
                fb_corners, fb_ids, fb_rejected = self.fallback_detector.detectMarkers(sharp)
            except cv2.error:
                fb_corners, fb_ids, fb_rejected = (), None, ()
            if fb_ids is not None:
                for i in range(len(fb_ids)):
                    tag_id = int(fb_ids[i][0])
                    if tag_id in self.valid_ids and tag_id not in seen_ids:
                        detections.append((tag_id, fb_corners[i].reshape(4, 2)))
                        seen_ids.add(tag_id)

        # Filter detections by quad geometric quality — removes false
        # positives from noise, reflections, or texture that happen to
        # decode as a valid tag ID.
        detections = [
            (tid, c2d) for tid, c2d in detections
            if _quad_quality(c2d) > 0.15
        ]
        seen_ids = {tid for tid, _ in detections}

        # Recover rejected candidates using predicted pose geometry.
        # Rejected quads failed bit-decoding (e.g. from blur) but may still
        # correspond to real tags. Match them against projected tag positions.
        all_rejected = list(rejected or []) + list(fb_rejected or [])
        if all_rejected and self.prev_rvec is not None:
            detections = self._recover_rejected(
                detections, seen_ids, all_rejected,
                self.prev_rvec, self.prev_tvec,
            )

        result["detections"] = detections
        result["n_tags"] = len(detections)
        result["tag_ids"] = [d[0] for d in detections]

        # Aggregate 2D-3D correspondences from ArUco detections
        obj_pts = []
        img_pts = []
        for tag_id, corners_2d in detections:
            obj_pts.append(self.tag_corner_map[tag_id])
            img_pts.append(corners_2d)

        # Optical flow: track corners from previous frame.
        # Use KF prediction as initial guess so LK can handle large displacements.
        # When ArUco finds 0 tags: use flow as sole source.
        # When ArUco finds few tags: augment with flow corners (excluding already-detected tags).
        used_flow = False
        flow_pred_rv, flow_pred_tv = None, None
        if self.pose_filter and self.pose_filter.is_initialized:
            pred = self.pose_filter.predict(timestamp)
            if pred is not None:
                flow_pred_rv, flow_pred_tv = pred
        elif self.prev_rvec is not None:
            flow_pred_rv, flow_pred_tv = self.prev_rvec, self.prev_tvec

        if len(detections) == 0:
            flow_result = self._track_corners_optflow(gray, flow_pred_rv, flow_pred_tv)
            if flow_result is not None:
                obj_pts.append(flow_result[0])
                img_pts.append(flow_result[1])
                used_flow = True

        if not obj_pts:
            self._prev_gray = gray.copy()  # still save for next frame's flow
            return self._store_latest(self._try_predict(timestamp, result), image)

        object_points = np.vstack(obj_pts).astype(np.float64)
        image_points = np.vstack(img_pts).astype(np.float64)

        # Identify visible faces
        for tag_id, _ in detections:
            for face_name, id_set in self.face_id_sets.items():
                if tag_id in id_set:
                    result["visible_faces"].add(face_name)

        # PnP initial guess: prefer KF-filtered prev pose; if unavailable
        # (after dropout/reset), use KF prediction to seed re-initialization.
        pnp_rv_guess = self.prev_rvec
        pnp_tv_guess = self.prev_tvec
        if pnp_rv_guess is None and self.pose_filter and self.pose_filter.is_initialized:
            pred = self.pose_filter.predict(timestamp)
            if pred is not None:
                pnp_rv_guess, pnp_tv_guess = pred

        # Solve PnP
        success, rvec, tvec, reproj_err, inliers = estimate_pose(
            object_points, image_points,
            self.camera_matrix, self.dist_coeffs,
            pnp_rv_guess, pnp_tv_guess,
        )

        # Per-tag reprojection outlier rejection: if a tag's mean corner
        # reprojection error is much higher than the median, drop it and
        # re-solve.  This catches false-positive detections that passed
        # the quad-quality gate but don't match the cube geometry.
        if success and not used_flow and len(detections) >= 3:
            projected, _ = cv2.projectPoints(
                object_points, rvec, tvec,
                self.camera_matrix, self.dist_coeffs,
            )
            projected = projected.reshape(-1, 2)
            # Compute per-tag mean reprojection error (4 corners each)
            per_tag_err = []
            for k in range(len(detections)):
                s, e = k * 4, (k + 1) * 4
                err = float(np.mean(np.linalg.norm(
                    image_points[s:e] - projected[s:e], axis=1)))
                per_tag_err.append(err)
            median_err = float(np.median(per_tag_err))
            # Keep tags whose error is within 3× the median (min 2 px)
            tag_reproj_thresh = max(median_err * 3.0, 2.0)
            keep = [i for i, e in enumerate(per_tag_err) if e <= tag_reproj_thresh]
            if len(keep) < len(detections) and len(keep) >= 1:
                detections = [detections[i] for i in keep]
                result["detections"] = detections
                result["n_tags"] = len(detections)
                result["tag_ids"] = [d[0] for d in detections]
                # Rebuild correspondences and re-solve
                obj_pts = [self.tag_corner_map[tid] for tid, _ in detections]
                img_pts = [c2d for _, c2d in detections]
                object_points = np.vstack(obj_pts).astype(np.float64)
                image_points = np.vstack(img_pts).astype(np.float64)
                # Recompute visible faces
                result["visible_faces"] = set()
                for tag_id, _ in detections:
                    for face_name, id_set in self.face_id_sets.items():
                        if tag_id in id_set:
                            result["visible_faces"].add(face_name)
                success, rvec, tvec, reproj_err, inliers = estimate_pose(
                    object_points, image_points,
                    self.camera_matrix, self.dist_coeffs,
                    pnp_rv_guess, pnp_tv_guess,
                )

        # Flow-tracked points are noisier — allow looser reproj
        max_reproj = 3.0
        if used_flow:
            max_reproj = 5.0
        if not success or reproj_err > max_reproj:
            return self._store_latest(self._try_predict(timestamp, result), image)

        # Reject flipped PnP solutions: verify that every detected face's
        # outward normal points toward the camera (negative z in camera frame).
        R_est, _ = cv2.Rodrigues(rvec)
        for face_name in result["visible_faces"]:
            for fd in FACE_DEFS:
                if fd[0] == face_name:
                    normal_obj = np.zeros(3)
                    normal_obj[fd[1]] = fd[2]
                    normal_cam = R_est @ normal_obj
                    # Outward normal should face camera (z < 0 in camera frame)
                    if normal_cam[2] > 0:
                        return self._store_latest(
                            self._try_predict(timestamp, result), image)
                    break

        # Temporal consistency: reject sudden large jumps.
        # Scale the gate by estimated velocity so fast motion isn't rejected.
        if self.prev_rvec is not None:
            jump_mm = float(np.linalg.norm(tvec.flatten() - self.prev_tvec.flatten()))
            R_prev, _ = cv2.Rodrigues(self.prev_rvec)
            angle = np.arccos(np.clip((np.trace(R_prev.T @ R_est) - 1) / 2, -1, 1))
            # Base gates + velocity-scaled headroom
            max_jump_mm = 100.0
            max_angle = np.radians(45)
            if self.pose_filter and self.pose_filter.is_initialized:
                speed = float(np.linalg.norm(self.pose_filter._x_t[3:6]))  # mm/s
                omega = float(np.linalg.norm(self.pose_filter._x_r[3:6]))  # rad/s
                dt = max(timestamp - self.pose_filter._last_ts, 1 / 60)
                max_jump_mm = max(100.0, speed * dt * 3.0)
                max_angle = max(np.radians(45), omega * dt * 3.0)
            if jump_mm > max_jump_mm or angle > max_angle:
                return self._store_latest(
                    self._try_predict(timestamp, result), image)
        else:
            # Re-initialization after dropout — require reasonable reproj error
            if reproj_err > 2.5:
                return self._store_latest(
                    self._try_predict(timestamp, result), image)

        # Kalman filter update
        n_inlier_count = len(inliers) if inliers is not None else 0
        # Inflate reproj error for flow measurements so KF trusts them less
        kf_reproj = reproj_err
        if used_flow:
            kf_reproj = reproj_err * 3.0
        kf_n_tags = max(len(detections), 1)
        if self.pose_filter:
            rvec, tvec = self.pose_filter.update(
                rvec, tvec, timestamp,
                reproj_error=kf_reproj,
                n_tags=kf_n_tags,
                n_inliers=n_inlier_count,
            )

        self.prev_rvec = rvec.copy()
        self.prev_tvec = tvec.copy()

        # Save corners for next frame's optical flow tracking.
        if detections:
            self._save_corners_for_flow(gray, detections)
        elif not used_flow:
            self._prev_gray = gray.copy()

        result["success"] = True
        result["rvec"] = rvec
        result["tvec"] = tvec
        T = np.eye(4)
        T[:3, :3], _ = cv2.Rodrigues(rvec)
        T[:3, 3] = tvec.flatten()
        result["T"] = T
        result["reproj_error"] = reproj_err
        result["n_inliers"] = n_inlier_count
        return self._store_latest(result, image)

    def draw_result(self, image: np.ndarray, result: dict) -> np.ndarray:
        """Draw detected markers, axes, and wireframe."""
        vis = image.copy()

        # Draw detected marker outlines (no ID text)
        if result["detections"]:
            for _, c2d in result["detections"]:
                pts = c2d.astype(np.int32)
                cv2.polylines(vis, [pts], True, (0, 255, 0), 2)

        if result["success"]:
            rvec, tvec = result["rvec"], result["tvec"]

            # Draw coordinate axes at cube center (manual to avoid OpenCV warnings)
            axis_len = float(max(self.config.box_dims) / 2)
            axes_3d = np.float64([
                [0, 0, 0], [axis_len, 0, 0], [0, axis_len, 0], [0, 0, axis_len]
            ])
            pts2d, _ = cv2.projectPoints(axes_3d, rvec, tvec,
                                         self.camera_matrix, self.dist_coeffs)
            pts2d = pts2d.reshape(-1, 2).astype(int)
            o = tuple(pts2d[0])
            cv2.line(vis, o, tuple(pts2d[1]), (0, 0, 255), 3)
            cv2.line(vis, o, tuple(pts2d[2]), (0, 255, 0), 3)
            cv2.line(vis, o, tuple(pts2d[3]), (255, 0, 0), 3)

            # Draw box wireframe
            projected, _ = cv2.projectPoints(
                self.box_corners_3d, rvec, tvec,
                self.camera_matrix, self.dist_coeffs,
            )
            pts = projected.reshape(-1, 2).astype(int)
            for i, j in self.box_edges:
                cv2.line(vis, tuple(pts[i]), tuple(pts[j]), (0, 255, 0), 2)

        # Overlay info text
        h = vis.shape[0]
        faces_str = ",".join(sorted(result["visible_faces"])) if result["visible_faces"] else "none"
        total = len(self.valid_ids)
        n = result["n_tags"]
        err = result["reproj_error"]
        lines = [
            f"Tags: {n}/{total}  Faces: {faces_str}",
            f"Reproj: {err:.2f}px" if result["success"] else "No pose",
        ]
        if result["success"]:
            t = result["tvec"].flatten() / 1000.0  # mm -> meters
            lines.append(f"T: [{t[0]:.4f}, {t[1]:.4f}, {t[2]:.4f}] m")
        for i, line in enumerate(lines):
            y = h - 10 - (len(lines) - 1 - i) * 25
            cv2.putText(vis, line, (10, y), cv2.FONT_HERSHEY_SIMPLEX,
                        0.6, (0, 255, 0), 2)

        return vis

    # -- Async (background detection) -----------------------------------------

    def start_async(self) -> None:
        """Start background detection thread.

        After calling this, use ``submit_frame()`` to feed frames and
        ``get_latest()`` to retrieve the most recent detection result.
        """
        if getattr(self, "_async_running", False):
            return
        self._async_running = True
        self._async_pending_frame: np.ndarray | None = None
        self._async_pending_lock = threading.Lock()
        self._async_pending_event = threading.Event()
        self._async_thread = threading.Thread(
            target=self._async_worker, daemon=True, name="aprilcube-async",
        )
        self._async_thread.start()

    def stop_async(self) -> None:
        """Stop the background detection thread."""
        if not getattr(self, "_async_running", False):
            return
        self._async_running = False
        self._async_pending_event.set()  # wake up worker so it can exit
        self._async_thread.join(timeout=2.0)

    def submit_frame(self, frame: np.ndarray) -> None:
        """Submit a frame for background detection (non-blocking).

        Always replaces any pending frame — if detection is slower than
        capture, intermediate frames are dropped automatically.
        """
        with self._async_pending_lock:
            self._async_pending_frame = frame
        self._async_pending_event.set()

    def get_latest(self) -> dict | None:
        """Return the most recent detection result, or None if no result yet."""
        with self._latest_lock:
            return self._latest_result

    def _async_worker(self) -> None:
        """Background worker: process pending frames as fast as possible."""
        while self._async_running:
            self._async_pending_event.wait()
            if not self._async_running:
                break
            self._async_pending_event.clear()
            # Grab the latest submitted frame
            with self._async_pending_lock:
                frame = self._async_pending_frame
                self._async_pending_frame = None
            if frame is not None:
                self.process_frame(frame)

    def world_pose(self, result: dict) -> np.ndarray | None:
        """Return 4x4 object-in-world transform from a process_frame result.

        Translation is in **meters**.
        If extrinsic (T_world_cam) is set, returns T_world_cam @ T_cam_obj.
        Otherwise returns T_cam_obj directly.
        Returns None if result has no pose.
        """
        if not result.get("success"):
            return None
        T = np.eye(4)
        T[:3, :3], _ = cv2.Rodrigues(result["rvec"])
        T[:3, 3] = result["tvec"].flatten() / 1000.0  # mm -> meters
        if self.extrinsic is not None:
            T = self.extrinsic @ T
        return T

    # -- Viser integration --------------------------------------------------

    def build_viser(self, port: int = 8080):
        """Create a viser server and start a background render thread.

        The scene is pre-populated with world frame, camera frame, ground grid,
        textured mesh (from model_dir/mujoco/cube.obj if available), object axes,
        and a GUI sidebar with camera feed. The background thread automatically
        renders the latest ``process_frame`` result — no manual update calls needed.

        Returns the ``viser.ViserServer`` for further customization.

        Requires ``pip install viser trimesh``.
        """
        import viser
        import viser.transforms as vtf

        server = viser.ViserServer(port=port)
        self._viser_server = server

        # World frame
        server.scene.add_frame(
            "/world", axes_length=0.05, axes_radius=0.002, origin_radius=0.0,
        )

        # Camera frame
        T_wc = self.extrinsic if self.extrinsic is not None else np.eye(4)
        cam_wxyz = tuple(vtf.SO3.from_matrix(T_wc[:3, :3]).wxyz)
        cam_pos = tuple(T_wc[:3, 3])
        server.scene.add_frame(
            "/camera", wxyz=cam_wxyz, position=cam_pos,
            axes_length=0.04, axes_radius=0.002, origin_radius=0.0,
        )

        # Ground grid
        grid_half = 0.3
        grid_step = 0.05
        grid_lines = []
        n = int(grid_half / grid_step)
        for i in range(-n, n + 1):
            p = i * grid_step
            grid_lines.append([[p, -grid_half, 0], [p, grid_half, 0]])
            grid_lines.append([[-grid_half, p, 0], [grid_half, p, 0]])
        server.scene.add_line_segments(
            "/ground_grid",
            points=np.array(grid_lines, dtype=np.float32),
            colors=(80, 80, 80),
            line_width=1.0,
        )

        # Object frame (created once, updated in _viser_loop via properties)
        self._viser_object_frame = server.scene.add_frame(
            "/object", axes_length=0.0, origin_radius=0.0,
        )

        # Textured mesh
        if self.model_dir is not None:
            from pathlib import Path
            obj_path = Path(self.model_dir) / "mujoco" / "cube.obj"
            if obj_path.exists():
                import trimesh
                mesh = trimesh.load(str(obj_path))
                server.scene.add_mesh_trimesh("/object/mesh", mesh)

        # Object axes
        axis_len = float(max(self.config.box_dims)) / 1000.0 * 0.6
        server.scene.add_frame(
            "/object/axes", axes_length=axis_len, axes_radius=0.002,
            origin_radius=0.0,
        )

        # GUI sidebar
        server.gui.set_panel_label("AprilCube")
        cam_folder = server.gui.add_folder("Camera Feed")
        with cam_folder:
            self._viser_gui_image = server.gui.add_image(
                np.zeros((240, 320, 3), dtype=np.uint8),
                label="Detection",
                format="jpeg",
                jpeg_quality=70,
            )
            self._viser_gui_status = server.gui.add_markdown(
                "*Waiting for detection...*"
            )

        # Start background render thread
        t = threading.Thread(target=self._viser_loop, daemon=True)
        t.start()

        return server

    def _viser_loop(self) -> None:
        """Background thread: render latest detection to viser at ~30 fps."""
        import viser.transforms as vtf

        server = self._viser_server
        while True:
            # Wait for a new frame
            counter = self._frame_counter
            if counter == self._viser_rendered_counter:
                time.sleep(0.01)
                continue
            self._viser_rendered_counter = counter

            with self._latest_lock:
                result = self._latest_result
                frame = self._latest_frame
            if result is None or frame is None:
                time.sleep(0.01)
                continue

            fps = self._fps

            # Update object pose
            T = self.world_pose(result)
            if T is not None:
                self._viser_object_frame.wxyz = vtf.SO3.from_matrix(T[:3, :3]).wxyz
                self._viser_object_frame.position = T[:3, 3]

            # 2D overlay -> GUI sidebar
            vis = self.draw_result(frame, result)
            cv2.putText(vis, f"FPS: {fps:.0f}", (10, 30),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
            vis_rgb = cv2.cvtColor(vis, cv2.COLOR_BGR2RGB)
            if self._viser_gui_image is not None:
                self._viser_gui_image.image = vis_rgb

            # Status text
            if self._viser_gui_status is not None:
                if result["success"]:
                    t = result["tvec"].flatten() / 1000.0  # mm -> meters
                    faces = ", ".join(sorted(result["visible_faces"]))
                    self._viser_gui_status.content = (
                        f"**Tags:** {result['n_tags']} | "
                        f"**Faces:** {faces}\n\n"
                        f"**Reproj:** {result['reproj_error']:.2f}px | "
                        f"**FPS:** {fps:.0f}\n\n"
                        f"**T:** [{t[0]:.4f}, {t[1]:.4f}, {t[2]:.4f}] m"
                    )
                else:
                    self._viser_gui_status.content = (
                        f"*No detection* | **FPS:** {fps:.0f}"
                    )



# ---------------------------------------------------------------------------
# Camera intrinsics
# ---------------------------------------------------------------------------
def load_camera_params(args, frame_shape: tuple[int, ...]
                       ) -> tuple[np.ndarray, np.ndarray]:
    """Load camera matrix and distortion coefficients."""
    if args.calib:
        with open(args.calib) as f:
            data = json.load(f)
        camera_matrix = np.array(data["camera_matrix"], dtype=np.float64)
        dist_coeffs = np.array(data.get("dist_coeffs", [0, 0, 0, 0, 0]), dtype=np.float64)
        return camera_matrix, dist_coeffs

    h, w = frame_shape[:2]
    if args.fx is not None:
        fx = args.fx
        fy = args.fy if args.fy is not None else args.fx
        cx = args.cx if args.cx is not None else w / 2
        cy = args.cy if args.cy is not None else h / 2
    else:
        # Rough default: assume FOV ~60deg -> fx ~ w
        fx = fy = float(w)
        cx, cy = w / 2, h / 2
        print("Warning: no calibration provided, using default intrinsics "
              f"(fx=fy={fx:.0f}, cx={cx:.0f}, cy={cy:.0f})", file=sys.stderr)

    camera_matrix = np.array([
        [fx, 0, cx],
        [0, fy, cy],
        [0, 0, 1],
    ], dtype=np.float64)
    dist_coeffs = np.zeros(5, dtype=np.float64)
    return camera_matrix, dist_coeffs


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(
        description="Detect ArUco/AprilTag cube and estimate 6-DOF pose.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="Examples:\n"
        "  %(prog)s --cube my_cube/config.json\n"
        "  %(prog)s --cube my_cube/config.json --camera 1\n"
        "  %(prog)s --cube my_cube/config.json --image photo.jpg --viz\n"
        "  %(prog)s --cube my_cube/config.json --calib calib.json --viz\n",
    )

    # Cube config
    parser.add_argument("--cube", type=str, required=True,
                        help="Path to config.json from generate_cube.py")

    # Input source (optional — defaults to webcam 0)
    input_grp = parser.add_mutually_exclusive_group()
    input_grp.add_argument("--camera", type=int, default=None, help="Camera index (default: 0)")
    input_grp.add_argument("--image", type=str, default=None, help="Image file path")
    input_grp.add_argument("--video", type=str, default=None, help="Video file path")

    # Camera intrinsics
    parser.add_argument("--calib", type=str, default=None, help="Calibration JSON file")
    parser.add_argument("--fx", type=float, default=None, help="Focal length X (pixels)")
    parser.add_argument("--fy", type=float, default=None, help="Focal length Y (pixels)")
    parser.add_argument("--cx", type=float, default=None, help="Principal point X")
    parser.add_argument("--cy", type=float, default=None, help="Principal point Y")

    # Options
    parser.add_argument("--no-filter", action="store_true", help="Disable temporal smoothing")
    parser.add_argument("--viz", action="store_true", help="Show debug visualization window")

    args = parser.parse_args()

    # Load cube config from JSON
    config, face_id_sets = load_cube_config(args.cube)
    bx, by, bz = config.box_dims
    print(f"Cube: {bx:.4g} x {by:.4g} x {bz:.4g} mm, "
          f"{len(config.tag_ids)} tags ({config.dict_name}), "
          f"cell={config.cell_size:.4g}mm")

    # Determine input source — default to webcam 0
    is_stream = args.image is None
    if args.image is not None:
        frame = cv2.imread(args.image)
        if frame is None:
            print(f"Error: cannot read {args.image}", file=sys.stderr)
            sys.exit(1)
        cap = None
    else:
        if args.video is not None:
            source = args.video
        else:
            source = args.camera if args.camera is not None else 0
        cap = cv2.VideoCapture(source)
        if not cap.isOpened():
            print(f"Error: cannot open camera/video {source}", file=sys.stderr)
            sys.exit(1)
        ret, frame = cap.read()
        if not ret:
            print("Error: cannot read first frame", file=sys.stderr)
            sys.exit(1)
        src_label = f"camera {source}" if args.video is None else args.video
        print(f"Input: {src_label} ({frame.shape[1]}x{frame.shape[0]})")

    # Load camera intrinsics
    camera_matrix, dist_coeffs = load_camera_params(args, frame.shape)
    print(f"Camera: fx={camera_matrix[0,0]:.1f} fy={camera_matrix[1,1]:.1f} "
          f"cx={camera_matrix[0,2]:.1f} cy={camera_matrix[1,2]:.1f}")

    # Create estimator
    enable_filter = not args.no_filter and is_stream
    estimator = CubePoseEstimator(config, face_id_sets, camera_matrix, dist_coeffs, enable_filter)

    # --- Single image mode ---
    if cap is None:
        result = estimator.process_frame(frame)
        if result["success"]:
            r = result["rvec"].flatten()
            t = result["tvec"].flatten() / 1000.0  # mm -> meters
            print(f"Pose: rvec=[{r[0]:.4f}, {r[1]:.4f}, {r[2]:.4f}] "
                  f"tvec=[{t[0]:.4f}, {t[1]:.4f}, {t[2]:.4f}] m")
            print(f"  reproj={result['reproj_error']:.2f}px, "
                  f"tags={result['n_tags']}/{len(config.tag_ids)}, "
                  f"faces={','.join(sorted(result['visible_faces']))}")
        else:
            print("No pose detected.")

        if args.viz:
            vis = estimator.draw_result(frame, result)
            cv2.imshow("detect_cube", vis)
            print("Press any key to exit.")
            cv2.waitKey(0)
            cv2.destroyAllWindows()
        return

    # --- Video / camera loop ---
    fps_timer = time.time()
    fps_count = 0
    fps_display = 0.0
    is_live = args.video is None
    video_fps = cap.get(cv2.CAP_PROP_FPS) if not is_live else 0
    frame_idx = 0

    while True:
        if frame is None:
            ret, frame = cap.read()
            if not ret:
                break

        if is_live:
            ts = time.monotonic()
        else:
            ts = frame_idx / video_fps if video_fps > 0 else frame_idx / 30.0
        frame_idx += 1

        result = estimator.process_frame(frame, timestamp=ts)

        # FPS counter
        fps_count += 1
        elapsed = time.time() - fps_timer
        if elapsed >= 1.0:
            fps_display = fps_count / elapsed
            fps_count = 0
            fps_timer = time.time()

        if result["success"]:
            r = result["rvec"].flatten()
            t = result["tvec"].flatten() / 1000.0  # mm -> meters
            faces = ",".join(sorted(result["visible_faces"]))
            print(f"\rrvec=[{r[0]:+.3f},{r[1]:+.3f},{r[2]:+.3f}] "
                  f"tvec=[{t[0]:+.4f},{t[1]:+.4f},{t[2]:+.4f}]m "
                  f"err={result['reproj_error']:.1f}px "
                  f"tags={result['n_tags']} faces={faces} "
                  f"fps={fps_display:.0f}",
                  end="", flush=True)

        if args.viz:
            vis = estimator.draw_result(frame, result)
            cv2.putText(vis, f"FPS: {fps_display:.0f}", (10, 30),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
            cv2.imshow("detect_cube", vis)
            key = cv2.waitKey(1) & 0xFF
            if key == 27 or key == ord("q"):
                break

        frame = None  # read next frame on next iteration

    print()
    cap.release()
    if args.viz:
        cv2.destroyAllWindows()


if __name__ == "__main__":
    main()
