#!/usr/bin/env python3
"""6-DOF pose detection for ArUco/AprilTag cubes generated by generate_cube.py.

Loads cube geometry from config.json (produced by generate_cube.py),
detects markers in camera/image/video, and estimates the cube's 6-DOF pose.
"""

import argparse
import json
import sys
import threading
import time
from collections import deque
from dataclasses import dataclass, field
from typing import NamedTuple

import cv2
import numpy as np

from aprilcube.generate import CubeConfig, DICT_MAP, FACE_DEFS


# ---------------------------------------------------------------------------
# Load cube config from JSON
# ---------------------------------------------------------------------------
def load_cube_config(path: str) -> tuple[CubeConfig, dict[str, set[int]]]:
    """Load CubeConfig and face→tag mapping from config.json."""
    with open(path) as f:
        data = json.load(f)

    from aprilcube.generate import parse_grid
    gx, gy, gz = parse_grid(data["grid"])
    dict_id = DICT_MAP[data["dict"]]

    config = CubeConfig(
        grid_x=gx, grid_y=gy, grid_z=gz,
        dict_id=dict_id, dict_name=data["dict"],
        tag_ids=data["tag_ids"],
        tag_size_mm=data["tag_size_mm"],
        margin_cells=data["margin_cells"],
        border_cells=data["border_cells"],
        cell_size_mm=data["cell_size_mm"],
    )
    config.compute()

    face_id_sets = {name: set(ids) for name, ids in data["faces"].items()}
    return config, face_id_sets


# ---------------------------------------------------------------------------
# 3D model: tag_id → corner positions on cube surface
# ---------------------------------------------------------------------------
def build_tag_corner_map(config: CubeConfig) -> dict[int, np.ndarray]:
    """Build mapping from tag_id to 3D corner positions (4x3, mm).

    Corners are ordered [TL, TR, BR, BL] as seen from outside the face,
    matching cv2.aruco.detectMarkers() corner ordering.
    """
    tag_corner_map: dict[int, np.ndarray] = {}
    id_cursor = 0
    mp = config.marker_pixels
    cs = config.cell_size

    for face_def in FACE_DEFS:
        _name, normal_ax, normal_sign, right_ax, right_sign, down_ax, down_sign = face_def
        face_rows, face_cols, down_cells, right_cells = config.face_layout(face_def)
        n_tags = face_rows * face_cols

        # Centering offsets (same logic as build_face_grid in generate_cube.py)
        tag_block_w = face_cols * mp + max(0, face_cols - 1) * config.margin_cells
        tag_block_h = face_rows * mp + max(0, face_rows - 1) * config.margin_cells
        row_off = (down_cells - tag_block_h) // 2
        col_off = (right_cells - tag_block_w) // 2

        right_half = config.box_dims[right_ax] / 2.0
        down_half = config.box_dims[down_ax] / 2.0
        face_pos = normal_sign * config.box_dims[normal_ax] / 2.0

        def cell_to_3d(row: float, col: float) -> np.ndarray:
            u = right_sign * (-right_half + col * cs)
            v = down_sign * (-down_half + row * cs)
            pt = np.zeros(3)
            pt[normal_ax] = face_pos
            pt[right_ax] = u
            pt[down_ax] = v
            return pt

        for r in range(face_rows):
            for c in range(face_cols):
                idx = r * face_cols + c
                if id_cursor + idx >= len(config.tag_ids):
                    break
                tag_id = config.tag_ids[id_cursor + idx]

                rs = row_off + r * (mp + config.margin_cells)
                cc = col_off + c * (mp + config.margin_cells)

                # [TL, TR, BR, BL] as seen from outside.
                # Tag patterns are np.fliplr'd in generate_cube.py, so the
                # detector's TL/TR are column-swapped relative to grid coords.
                corners_3d = np.array([
                    cell_to_3d(rs, cc + mp),       # TL
                    cell_to_3d(rs, cc),             # TR
                    cell_to_3d(rs + mp, cc),        # BR
                    cell_to_3d(rs + mp, cc + mp),   # BL
                ], dtype=np.float64)

                tag_corner_map[tag_id] = corners_3d

        id_cursor += n_tags

    return tag_corner_map




# ---------------------------------------------------------------------------
# ArUco detector with tuned parameters
# ---------------------------------------------------------------------------
def create_detector(dict_id: int, fast: bool = False) -> cv2.aruco.ArucoDetector:
    """Create an ArUco detector tuned for 3D-printed markers.

    Args:
        dict_id: ArUco dictionary ID.
        fast: If True, use faster parameters better suited for real-time webcam use.
    """
    dictionary = cv2.aruco.getPredefinedDictionary(dict_id)
    params = cv2.aruco.DetectorParameters()

    if fast:
        # Skip subpix refinement for speed (CONTOUR can crash on some frames)
        params.cornerRefinementMethod = cv2.aruco.CORNER_REFINE_NONE

        # Fewer threshold passes
        params.adaptiveThreshWinSizeMin = 5
        params.adaptiveThreshWinSizeMax = 41
        params.adaptiveThreshWinSizeStep = 12

        # Tighter candidate filtering — reject tiny/huge quads early
        params.minMarkerPerimeterRate = 0.03
        params.maxMarkerPerimeterRate = 4.0
        params.polygonalApproxAccuracyRate = 0.05
        params.minCornerDistanceRate = 0.05
        params.minDistanceToBorder = 2

        params.perspectiveRemovePixelPerCell = 6
        params.perspectiveRemoveIgnoredMarginPerCell = 0.13
        params.errorCorrectionRate = 0.6
    else:
        # Sub-pixel corner refinement — critical for PnP accuracy
        params.cornerRefinementMethod = cv2.aruco.CORNER_REFINE_SUBPIX
        params.cornerRefinementWinSize = 5
        params.cornerRefinementMaxIterations = 50
        params.cornerRefinementMinAccuracy = 0.01

        # Adaptive thresholding — wider range for 3D-printed surface texture
        params.adaptiveThreshWinSizeMin = 3
        params.adaptiveThreshWinSizeMax = 53
        params.adaptiveThreshWinSizeStep = 4

        # Candidate filtering — relax for oblique views
        params.minMarkerPerimeterRate = 0.01
        params.maxMarkerPerimeterRate = 4.0
        params.polygonalApproxAccuracyRate = 0.05
        params.minCornerDistanceRate = 0.02
        params.minDistanceToBorder = 1

        # Bit decoding — higher sampling for oblique perspectives
        params.perspectiveRemovePixelPerCell = 8
        params.perspectiveRemoveIgnoredMarginPerCell = 0.13
        params.errorCorrectionRate = 0.6

    return cv2.aruco.ArucoDetector(dictionary, params)


# ---------------------------------------------------------------------------
# Pose estimation
# ---------------------------------------------------------------------------
def estimate_pose(
    object_points: np.ndarray,
    image_points: np.ndarray,
    camera_matrix: np.ndarray,
    dist_coeffs: np.ndarray,
    prev_rvec: np.ndarray | None = None,
    prev_tvec: np.ndarray | None = None,
) -> tuple[bool, np.ndarray | None, np.ndarray | None, float, np.ndarray | None]:
    """Estimate 6-DOF pose from 2D-3D correspondences.

    Returns (success, rvec, tvec, reproj_error, inliers).
    """
    n_points = object_points.shape[0]
    if n_points < 4:
        return False, None, None, float("inf"), None

    use_guess = prev_rvec is not None and prev_tvec is not None

    if n_points >= 6:
        success, rvec, tvec, inliers = cv2.solvePnPRansac(
            objectPoints=object_points,
            imagePoints=image_points,
            cameraMatrix=camera_matrix,
            distCoeffs=dist_coeffs,
            rvec=prev_rvec.copy() if use_guess else None,
            tvec=prev_tvec.copy() if use_guess else None,
            useExtrinsicGuess=use_guess,
            iterationsCount=200,
            reprojectionError=3.0,
            confidence=0.99,
            flags=cv2.SOLVEPNP_SQPNP,
        )
    else:
        success, rvec, tvec = cv2.solvePnP(
            objectPoints=object_points,
            imagePoints=image_points,
            cameraMatrix=camera_matrix,
            distCoeffs=dist_coeffs,
            rvec=prev_rvec.copy() if use_guess else None,
            tvec=prev_tvec.copy() if use_guess else None,
            useExtrinsicGuess=use_guess,
            flags=cv2.SOLVEPNP_SQPNP,
        )
        inliers = np.arange(n_points).reshape(-1, 1) if success else None

    if not success:
        return False, None, None, float("inf"), None

    # Refine with Levenberg-Marquardt on inliers
    if inliers is not None and len(inliers) >= 4:
        idx = inliers.flatten()
        rvec, tvec = cv2.solvePnPRefineLM(
            objectPoints=object_points[idx],
            imagePoints=image_points[idx],
            cameraMatrix=camera_matrix,
            distCoeffs=dist_coeffs,
            rvec=rvec,
            tvec=tvec,
        )

    # Reprojection error
    projected, _ = cv2.projectPoints(object_points, rvec, tvec, camera_matrix, dist_coeffs)
    projected = projected.reshape(-1, 2)
    reproj_err = float(np.mean(np.linalg.norm(image_points - projected, axis=1)))

    return success, rvec, tvec, reproj_err, inliers


# ---------------------------------------------------------------------------
# Temporal filter
# ---------------------------------------------------------------------------
class PoseFilter:
    """EMA filter for smoothing pose in video."""

    def __init__(self, alpha: float = 0.3, max_jump_mm: float = 50.0,
                 max_jump_deg: float = 30.0):
        self.alpha = alpha
        self.max_jump_mm = max_jump_mm
        self.max_jump_deg = max_jump_deg
        self.rvec: np.ndarray | None = None
        self.tvec: np.ndarray | None = None

    def update(self, rvec: np.ndarray, tvec: np.ndarray
               ) -> tuple[np.ndarray, np.ndarray]:
        if self.rvec is None:
            self.rvec = rvec.copy()
            self.tvec = tvec.copy()
            return self.rvec.copy(), self.tvec.copy()

        dt = float(np.linalg.norm(tvec - self.tvec))
        R_prev, _ = cv2.Rodrigues(self.rvec)
        R_curr, _ = cv2.Rodrigues(rvec)
        R_diff = R_curr @ R_prev.T
        angle = np.arccos(np.clip((np.trace(R_diff) - 1) / 2, -1, 1))
        angle_deg = float(np.degrees(angle))

        if dt > self.max_jump_mm or angle_deg > self.max_jump_deg:
            self.rvec = rvec.copy()
            self.tvec = tvec.copy()
        else:
            self.tvec = self.alpha * tvec + (1 - self.alpha) * self.tvec
            # SLERP-style rotation interpolation (linear EMA on Rodrigues
            # vectors is wrong — axis direction and angle don't blend linearly).
            # R_filtered = R_prev @ expm(alpha * logm(R_prev^T @ R_curr))
            R_delta = R_prev.T @ R_curr
            delta_rvec, _ = cv2.Rodrigues(R_delta)
            scaled_delta, _ = cv2.Rodrigues(self.alpha * delta_rvec)
            R_filtered = R_prev @ scaled_delta
            self.rvec, _ = cv2.Rodrigues(R_filtered)

        return self.rvec.copy(), self.tvec.copy()

    def reset(self):
        self.rvec = None
        self.tvec = None


# ---------------------------------------------------------------------------
# Quaternion utilities (Hamilton convention: q = [w, x, y, z])
# ---------------------------------------------------------------------------
def _rvec_to_quat(rvec: np.ndarray) -> np.ndarray:
    """Rodrigues (3,) or (3,1) → unit quaternion [w, x, y, z]."""
    r = rvec.flatten()
    angle = float(np.linalg.norm(r))
    if angle < 1e-10:
        return np.array([1.0, 0.0, 0.0, 0.0])
    axis = r / angle
    ha = angle / 2
    sa = np.sin(ha)
    return np.array([np.cos(ha), sa * axis[0], sa * axis[1], sa * axis[2]])


def _quat_to_rvec(q: np.ndarray) -> np.ndarray:
    """Unit quaternion [w, x, y, z] → Rodrigues (3, 1)."""
    w, x, y, z = q
    sin_ha = np.sqrt(x * x + y * y + z * z)
    if sin_ha < 1e-10:
        return np.zeros((3, 1))
    angle = 2.0 * np.arctan2(sin_ha, abs(w))
    if w < 0:
        angle = -angle
    axis = np.array([x, y, z]) / sin_ha
    return (angle * axis).reshape(3, 1)


def _quat_mul(q1: np.ndarray, q2: np.ndarray) -> np.ndarray:
    """Hamilton product q1 * q2."""
    w1, x1, y1, z1 = q1
    w2, x2, y2, z2 = q2
    return np.array([
        w1 * w2 - x1 * x2 - y1 * y2 - z1 * z2,
        w1 * x2 + x1 * w2 + y1 * z2 - z1 * y2,
        w1 * y2 - x1 * z2 + y1 * w2 + z1 * x2,
        w1 * z2 + x1 * y2 - y1 * x2 + z1 * w2,
    ])


def _quat_conj(q: np.ndarray) -> np.ndarray:
    return np.array([q[0], -q[1], -q[2], -q[3]])


def _quat_to_rotvec(q: np.ndarray) -> np.ndarray:
    """Quaternion → rotation vector (3,). Handles small angles."""
    w, x, y, z = q
    sin_ha = np.sqrt(x * x + y * y + z * z)
    if sin_ha < 1e-10:
        return 2.0 * np.array([x, y, z])
    angle = 2.0 * np.arctan2(sin_ha, abs(w))
    if w < 0:
        angle = -angle
    return angle * np.array([x, y, z]) / sin_ha


# ---------------------------------------------------------------------------
# Kalman pose filter
# ---------------------------------------------------------------------------
class PoseSnapshot(NamedTuple):
    """Immutable record of one filter output."""
    timestamp: float
    rvec: np.ndarray
    tvec: np.ndarray
    velocity: np.ndarray      # (3,) mm/s
    omega: np.ndarray          # (3,) rad/s
    measurement_used: bool
    reproj_error: float
    n_tags: int


@dataclass
class KalmanFilterConfig:
    """Tuning knobs for KalmanPoseFilter."""
    # Process noise (constant-velocity model)
    sigma_accel: float = 2000.0      # mm/s², translation
    sigma_alpha: float = 30.0        # rad/s², rotation

    # Base measurement noise (scaled adaptively per frame)
    base_sigma_t: float = 1.0        # mm
    base_sigma_r: float = 0.005      # rad

    # Innovation gating (Mahalanobis distance thresholds)
    mahal_gate: float = 16.0         # soft reject above this
    mahal_hard_reset: float = 100.0  # hard re-init above this
    max_outliers_before_reset: int = 3

    # Initialization covariance
    init_sigma_pos: float = 50.0     # mm
    init_sigma_vel: float = 500.0    # mm/s
    init_sigma_rot: float = 0.5      # rad
    init_sigma_omega: float = 5.0    # rad/s

    # Limits
    max_predict_dt: float = 0.1      # seconds without measurement before reset

    # History buffer
    history_size: int = 300          # ~10 s at 30 fps


class KalmanPoseFilter:
    """Error-state Kalman filter for 6-DOF pose tracking.

    Translation: standard linear KF, state = [x, y, z, vx, vy, vz].
    Rotation:    multiplicative error-state KF on unit quaternion,
                 error state = [dθx, dθy, dθz, ωx, ωy, ωz].

    The nominal quaternion is maintained separately and updated
    multiplicatively after each correction step.
    """

    def __init__(self, config: KalmanFilterConfig | None = None):
        self.cfg = config or KalmanFilterConfig()
        self._initialized = False

        # Translation KF: [px, py, pz, vx, vy, vz]
        self._x_t = np.zeros(6)
        self._P_t = np.eye(6)

        # Rotation error-state KF: [dθx, dθy, dθz, ωx, ωy, ωz]
        self._q = np.array([1.0, 0.0, 0.0, 0.0])  # nominal quaternion
        self._x_r = np.zeros(6)
        self._P_r = np.eye(6)

        # Shared measurement matrix H = [I_3 | 0_3]
        self._H = np.zeros((3, 6))
        self._H[:3, :3] = np.eye(3)

        self._last_ts: float = 0.0
        self._outlier_count = 0
        self._history: deque[PoseSnapshot] = deque(maxlen=self.cfg.history_size)

    # -- public interface ---------------------------------------------------

    def update(
        self,
        rvec: np.ndarray,
        tvec: np.ndarray,
        timestamp: float,
        reproj_error: float = 1.0,
        n_tags: int = 1,
        n_inliers: int = 4,
    ) -> tuple[np.ndarray, np.ndarray]:
        """Incorporate a PnP measurement. Returns (filtered_rvec, filtered_tvec)."""
        if not self._initialized:
            self._init_state(rvec, tvec, timestamp)
            self._snap(timestamp, True, reproj_error, n_tags)
            return self._output()

        dt = timestamp - self._last_ts
        if dt <= 0:
            dt = 1.0 / 30.0
        if dt > self.cfg.max_predict_dt:
            self._init_state(rvec, tvec, timestamp)
            self._snap(timestamp, True, reproj_error, n_tags)
            return self._output()

        # 1) predict
        self._predict(dt)
        self._last_ts = timestamp

        # 2) adaptive measurement noise
        R_t, R_r = self._adaptive_R(reproj_error, n_tags, n_inliers)

        # 3) translation innovation
        z_t = tvec.flatten()
        H = self._H
        innov_t = z_t - H @ self._x_t
        S_t = H @ self._P_t @ H.T + R_t
        mahal_t = float(innov_t @ np.linalg.solve(S_t, innov_t))

        # 4) rotation innovation (error-state)
        q_meas = _rvec_to_quat(rvec)
        if np.dot(self._q, q_meas) < 0:
            q_meas = -q_meas
        dq = _quat_mul(_quat_conj(self._q), q_meas)
        innov_r = _quat_to_rotvec(dq)
        S_r = H @ self._P_r @ H.T + R_r
        mahal_r = float(innov_r @ np.linalg.solve(S_r, innov_r))

        mahal = mahal_t + mahal_r

        # 5) gating
        if mahal > self.cfg.mahal_hard_reset or \
                self._outlier_count >= self.cfg.max_outliers_before_reset:
            self._init_state(rvec, tvec, timestamp)
            self._snap(timestamp, True, reproj_error, n_tags)
            return self._output()
        if mahal > self.cfg.mahal_gate:
            R_t = R_t * 10.0
            R_r = R_r * 10.0
            S_t = H @ self._P_t @ H.T + R_t
            S_r = H @ self._P_r @ H.T + R_r
            self._outlier_count += 1
        else:
            self._outlier_count = 0

        # 6) Kalman update — translation (Joseph form)
        K_t = self._P_t @ H.T @ np.linalg.inv(S_t)
        self._x_t += K_t @ innov_t
        I_KH = np.eye(6) - K_t @ H
        self._P_t = I_KH @ self._P_t @ I_KH.T + K_t @ R_t @ K_t.T

        # 7) Kalman update — rotation error-state (Joseph form)
        K_r = self._P_r @ H.T @ np.linalg.inv(S_r)
        self._x_r += K_r @ innov_r
        I_KH_r = np.eye(6) - K_r @ H
        self._P_r = I_KH_r @ self._P_r @ I_KH_r.T + K_r @ R_r @ K_r.T

        # 8) fold error rotation into nominal quaternion, reset error
        dq_corr = _rvec_to_quat(self._x_r[:3])
        self._q = _quat_mul(self._q, dq_corr)
        self._q /= np.linalg.norm(self._q)
        self._x_r[:3] = 0.0

        # symmetry guard
        self._P_t = (self._P_t + self._P_t.T) / 2
        self._P_r = (self._P_r + self._P_r.T) / 2

        self._snap(timestamp, True, reproj_error, n_tags)
        return self._output()

    def predict(self, timestamp: float) -> tuple[np.ndarray, np.ndarray] | None:
        """Predict pose at *timestamp* without a measurement.

        Returns (rvec, tvec) or None if not initialized / dt too large.
        """
        if not self._initialized:
            return None
        dt = timestamp - self._last_ts
        if dt < 0 or dt > self.cfg.max_predict_dt:
            return None

        # translate
        F = np.eye(6)
        F[0, 3] = F[1, 4] = F[2, 5] = dt
        x_t_pred = F @ self._x_t
        tvec = x_t_pred[:3].reshape(3, 1)

        # rotate
        omega = self._x_r[3:6]
        angle = float(np.linalg.norm(omega)) * dt
        if angle > 1e-10:
            axis = omega / np.linalg.norm(omega)
            sa = np.sin(angle / 2)
            dq = np.array([np.cos(angle / 2), sa * axis[0], sa * axis[1], sa * axis[2]])
            q_pred = _quat_mul(self._q, dq)
            q_pred /= np.linalg.norm(q_pred)
        else:
            q_pred = self._q.copy()
        rvec = _quat_to_rvec(q_pred)

        return rvec, tvec

    def get_velocity(self) -> tuple[np.ndarray, np.ndarray] | None:
        """Return (linear_vel mm/s, angular_vel rad/s) or None."""
        if not self._initialized:
            return None
        return self._x_t[3:6].copy(), self._x_r[3:6].copy()

    def reset(self):
        self._initialized = False
        self._x_t[:] = 0
        self._P_t = np.eye(6)
        self._q = np.array([1.0, 0.0, 0.0, 0.0])
        self._x_r[:] = 0
        self._P_r = np.eye(6)
        self._outlier_count = 0

    @property
    def is_initialized(self) -> bool:
        return self._initialized

    @property
    def history(self) -> deque[PoseSnapshot]:
        return self._history

    # -- internals ----------------------------------------------------------

    def _init_state(self, rvec: np.ndarray, tvec: np.ndarray, ts: float):
        self._x_t[:3] = tvec.flatten()
        self._x_t[3:] = 0.0
        self._q = _rvec_to_quat(rvec)
        self._x_r[:] = 0.0

        c = self.cfg
        self._P_t = np.diag([
            c.init_sigma_pos ** 2, c.init_sigma_pos ** 2, c.init_sigma_pos ** 2,
            c.init_sigma_vel ** 2, c.init_sigma_vel ** 2, c.init_sigma_vel ** 2,
        ])
        self._P_r = np.diag([
            c.init_sigma_rot ** 2, c.init_sigma_rot ** 2, c.init_sigma_rot ** 2,
            c.init_sigma_omega ** 2, c.init_sigma_omega ** 2, c.init_sigma_omega ** 2,
        ])
        self._last_ts = ts
        self._initialized = True
        self._outlier_count = 0

    def _predict(self, dt: float):
        # translation
        F = np.eye(6)
        F[0, 3] = F[1, 4] = F[2, 5] = dt
        self._x_t = F @ self._x_t
        self._P_t = F @ self._P_t @ F.T + self._build_Q(dt, self.cfg.sigma_accel)

        # rotate nominal quaternion by angular velocity
        omega = self._x_r[3:6]
        angle = float(np.linalg.norm(omega)) * dt
        if angle > 1e-10:
            axis = omega / np.linalg.norm(omega)
            sa = np.sin(angle / 2)
            dq = np.array([np.cos(angle / 2), sa * axis[0], sa * axis[1], sa * axis[2]])
            self._q = _quat_mul(self._q, dq)
            self._q /= np.linalg.norm(self._q)

        # rotation error-state
        F_r = np.eye(6)
        F_r[0, 3] = F_r[1, 4] = F_r[2, 5] = dt
        self._x_r = F_r @ self._x_r
        self._x_r[:3] = 0.0  # error always reset
        self._P_r = F_r @ self._P_r @ F_r.T + self._build_Q(dt, self.cfg.sigma_alpha)

    @staticmethod
    def _build_Q(dt: float, sigma: float) -> np.ndarray:
        s2 = sigma * sigma
        dt2 = dt * dt
        dt3 = dt2 * dt
        dt4 = dt3 * dt
        Q = np.zeros((6, 6))
        for i in range(3):
            Q[i, i] = s2 * dt4 / 4
            Q[i, i + 3] = s2 * dt3 / 2
            Q[i + 3, i] = s2 * dt3 / 2
            Q[i + 3, i + 3] = s2 * dt2
        return Q

    def _adaptive_R(self, reproj: float, n_tags: int, n_inliers: int
                    ) -> tuple[np.ndarray, np.ndarray]:
        reproj_factor = max(1.0, reproj ** 2)
        tag_factor = max(1.0, 4.0 / max(n_tags, 1))
        n_pts = n_tags * 4
        inlier_ratio = n_inliers / max(n_pts, 1)
        inlier_factor = max(1.0, 1.0 / max(inlier_ratio, 0.3))
        scale = reproj_factor * tag_factor * inlier_factor

        st = self.cfg.base_sigma_t * scale
        sr = self.cfg.base_sigma_r * scale
        return (st ** 2) * np.eye(3), (sr ** 2) * np.eye(3)

    def _output(self) -> tuple[np.ndarray, np.ndarray]:
        rvec = _quat_to_rvec(self._q)
        tvec = self._x_t[:3].reshape(3, 1)
        return rvec, tvec

    def _snap(self, ts: float, meas: bool, reproj: float, n_tags: int):
        rvec, tvec = self._output()
        self._history.append(PoseSnapshot(
            timestamp=ts,
            rvec=rvec.copy(),
            tvec=tvec.copy(),
            velocity=self._x_t[3:6].copy(),
            omega=self._x_r[3:6].copy(),
            measurement_used=meas,
            reproj_error=reproj,
            n_tags=n_tags,
        ))


# ---------------------------------------------------------------------------
# Main estimator
# ---------------------------------------------------------------------------
class CubePoseEstimator:
    """Detects ArUco tags on a cube and estimates 6-DOF pose."""

    def __init__(self, config: CubeConfig, face_id_sets: dict[str, set[int]],
                 camera_matrix: np.ndarray, dist_coeffs: np.ndarray,
                 enable_filter: bool = True,
                 filter_config: KalmanFilterConfig | None = None,
                 fast: bool = False,
                 extrinsic: np.ndarray | None = None,
                 model_dir: str | None = None):
        self.config = config
        self.camera_matrix = camera_matrix
        self.dist_coeffs = dist_coeffs
        self.extrinsic = np.asarray(extrinsic, dtype=np.float64) if extrinsic is not None else None
        self.model_dir = model_dir

        self.tag_corner_map = build_tag_corner_map(config)
        self.valid_ids = set(self.tag_corner_map.keys())
        self.face_id_sets = face_id_sets
        self.detector = create_detector(config.dict_id, fast=fast)
        self.pose_filter: KalmanPoseFilter | None = (
            KalmanPoseFilter(filter_config) if enable_filter else None
        )

        self.prev_rvec: np.ndarray | None = None
        self.prev_tvec: np.ndarray | None = None

        # Box wireframe corners for visualization
        bx, by, bz = config.box_dims
        hx, hy, hz = bx / 2, by / 2, bz / 2
        self.box_corners_3d = np.array([
            [-hx, -hy, -hz], [+hx, -hy, -hz], [+hx, +hy, -hz], [-hx, +hy, -hz],
            [-hx, -hy, +hz], [+hx, -hy, +hz], [+hx, +hy, +hz], [-hx, +hy, +hz],
        ], dtype=np.float64)
        self.box_edges = [
            (0, 1), (1, 2), (2, 3), (3, 0),  # bottom
            (4, 5), (5, 6), (6, 7), (7, 4),  # top
            (0, 4), (1, 5), (2, 6), (3, 7),  # verticals
        ]

        # Latest detection state (read by viser background thread)
        self._latest_result: dict | None = None
        self._latest_frame: np.ndarray | None = None
        self._latest_lock = threading.Lock()
        self._frame_counter = 0
        self._fps = 0.0
        self._fps_t = time.time()
        self._fps_n = 0

        # Viser state (populated by build_viser)
        self._viser_gui_image = None
        self._viser_gui_status = None
        self._viser_server = None
        self._viser_rendered_counter = -1

    def _try_predict(self, timestamp: float, result: dict) -> dict:
        """Try KF prediction as fallback when detection/PnP fails."""
        if self.pose_filter and self.pose_filter.is_initialized:
            pred = self.pose_filter.predict(timestamp)
            if pred is not None:
                rvec, tvec = pred
                result["success"] = True
                result["rvec"] = rvec
                result["tvec"] = tvec
                result["predicted"] = True
                # Don't update prev_rvec/tvec — keep last measured pose
                # as PnP initial guess to avoid feedback from bad predictions.
                return result
        # prediction unavailable — hard reset
        self.prev_rvec = None
        self.prev_tvec = None
        if self.pose_filter:
            self.pose_filter.reset()
        return result

    def _store_latest(self, result: dict, frame: np.ndarray) -> dict:
        """Store the latest result/frame for the viser background thread."""
        with self._latest_lock:
            self._latest_result = result
            self._latest_frame = frame
            self._frame_counter += 1
        # FPS tracking
        self._fps_n += 1
        elapsed = time.time() - self._fps_t
        if elapsed >= 1.0:
            self._fps = self._fps_n / elapsed
            self._fps_n = 0
            self._fps_t = time.time()
        return result

    def process_frame(self, image: np.ndarray,
                      timestamp: float | None = None) -> dict:
        """Process a single frame and return pose result.

        Args:
            image: BGR or grayscale frame.
            timestamp: Monotonic time in seconds for this frame.
                       If None, uses ``time.monotonic()``.
        """
        if timestamp is None:
            timestamp = time.monotonic()

        result = {
            "success": False, "rvec": None, "tvec": None,
            "reproj_error": float("inf"), "n_tags": 0,
            "n_inliers": 0, "detections": [], "tag_ids": [],
            "visible_faces": set(), "predicted": False,
        }

        # Detect
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) if len(image.shape) == 3 else image
        corners_list, ids, _ = self.detector.detectMarkers(gray)
        if ids is None:
            return self._store_latest(self._try_predict(timestamp, result), image)

        # Filter to valid cube IDs
        detections = []
        for i in range(len(ids)):
            tag_id = int(ids[i][0])
            if tag_id in self.valid_ids:
                corners_2d = corners_list[i].reshape(4, 2)
                detections.append((tag_id, corners_2d))

        result["detections"] = detections
        result["n_tags"] = len(detections)
        result["tag_ids"] = [d[0] for d in detections]

        if not detections:
            return self._store_latest(self._try_predict(timestamp, result), image)

        # Identify visible faces
        for tag_id, _ in detections:
            for face_name, id_set in self.face_id_sets.items():
                if tag_id in id_set:
                    result["visible_faces"].add(face_name)

        # Aggregate 2D-3D correspondences
        obj_pts = []
        img_pts = []
        for tag_id, corners_2d in detections:
            obj_pts.append(self.tag_corner_map[tag_id])
            img_pts.append(corners_2d)
        object_points = np.vstack(obj_pts).astype(np.float64)
        image_points = np.vstack(img_pts).astype(np.float64)

        # Use last measured pose as PnP initial guess (not KF prediction,
        # which can drift and pull PnP to wrong solutions)
        pnp_rv_guess = self.prev_rvec
        pnp_tv_guess = self.prev_tvec

        # Solve PnP
        success, rvec, tvec, reproj_err, inliers = estimate_pose(
            object_points, image_points,
            self.camera_matrix, self.dist_coeffs,
            pnp_rv_guess, pnp_tv_guess,
        )

        if not success or reproj_err > 5.0:
            return self._store_latest(self._try_predict(timestamp, result), image)

        # Reject flipped PnP solutions: verify that every detected face's
        # outward normal points toward the camera (negative z in camera frame).
        R_est, _ = cv2.Rodrigues(rvec)
        for face_name in result["visible_faces"]:
            for fd in FACE_DEFS:
                if fd[0] == face_name:
                    normal_obj = np.zeros(3)
                    normal_obj[fd[1]] = fd[2]
                    normal_cam = R_est @ normal_obj
                    # Outward normal should face camera (z < 0 in camera frame)
                    if normal_cam[2] > 0:
                        return self._store_latest(
                            self._try_predict(timestamp, result), image)
                    break

        # Temporal consistency: reject sudden large jumps from previous pose.
        if self.prev_rvec is not None:
            dt = float(np.linalg.norm(tvec.flatten() - self.prev_tvec.flatten()))
            R_prev, _ = cv2.Rodrigues(self.prev_rvec)
            angle = np.arccos(np.clip((np.trace(R_prev.T @ R_est) - 1) / 2, -1, 1))
            # Allow generous thresholds — only reject clearly wrong flips,
            # not fast legitimate motion.
            dist_to_cam = float(np.linalg.norm(tvec))
            if dt > dist_to_cam * 0.5 or angle > np.radians(60):
                return self._store_latest(
                    self._try_predict(timestamp, result), image)

        # Kalman filter update
        n_inlier_count = len(inliers) if inliers is not None else 0
        if self.pose_filter:
            rvec, tvec = self.pose_filter.update(
                rvec, tvec, timestamp,
                reproj_error=reproj_err,
                n_tags=len(detections),
                n_inliers=n_inlier_count,
            )

        self.prev_rvec = rvec.copy()
        self.prev_tvec = tvec.copy()

        result["success"] = True
        result["rvec"] = rvec
        result["tvec"] = tvec
        result["reproj_error"] = reproj_err
        result["n_inliers"] = n_inlier_count
        return self._store_latest(result, image)

    def draw_result(self, image: np.ndarray, result: dict) -> np.ndarray:
        """Draw detected markers, axes, and wireframe."""
        vis = image.copy()

        # Draw detected marker outlines (no ID text)
        if result["detections"]:
            for _, c2d in result["detections"]:
                pts = c2d.astype(np.int32)
                cv2.polylines(vis, [pts], True, (0, 255, 0), 2)

        if result["success"]:
            rvec, tvec = result["rvec"], result["tvec"]

            # Draw coordinate axes at cube center
            axis_len = float(max(self.config.box_dims) / 2)
            cv2.drawFrameAxes(vis, self.camera_matrix, self.dist_coeffs,
                              rvec, tvec, axis_len, 3)

            # Draw box wireframe
            projected, _ = cv2.projectPoints(
                self.box_corners_3d, rvec, tvec,
                self.camera_matrix, self.dist_coeffs,
            )
            pts = projected.reshape(-1, 2).astype(int)
            for i, j in self.box_edges:
                cv2.line(vis, tuple(pts[i]), tuple(pts[j]), (0, 255, 0), 2)

        # Overlay info text
        h = vis.shape[0]
        faces_str = ",".join(sorted(result["visible_faces"])) if result["visible_faces"] else "none"
        total = len(self.valid_ids)
        n = result["n_tags"]
        err = result["reproj_error"]
        lines = [
            f"Tags: {n}/{total}  Faces: {faces_str}",
            f"Reproj: {err:.2f}px" if result["success"] else "No pose",
        ]
        if result["success"]:
            t = result["tvec"].flatten()
            lines.append(f"T: [{t[0]:.1f}, {t[1]:.1f}, {t[2]:.1f}] mm")
        for i, line in enumerate(lines):
            y = h - 10 - (len(lines) - 1 - i) * 25
            cv2.putText(vis, line, (10, y), cv2.FONT_HERSHEY_SIMPLEX,
                        0.6, (0, 255, 0), 2)

        return vis

    def world_pose(self, result: dict) -> np.ndarray | None:
        """Return 4x4 object-in-world transform from a process_frame result.

        If extrinsic (T_world_cam) is set, returns T_world_cam @ T_cam_obj.
        Otherwise returns T_cam_obj directly.
        Returns None if result has no pose.
        """
        if not result.get("success"):
            return None
        T = np.eye(4)
        T[:3, :3], _ = cv2.Rodrigues(result["rvec"])
        T[:3, 3] = result["tvec"].flatten()
        if self.extrinsic is not None:
            T = self.extrinsic @ T
        return T

    # -- Viser integration --------------------------------------------------

    def build_viser(self, port: int = 8080):
        """Create a viser server and start a background render thread.

        The scene is pre-populated with world frame, camera frame, ground grid,
        textured mesh (from model_dir/mujoco/cube.obj if available), object axes,
        and a GUI sidebar with camera feed. The background thread automatically
        renders the latest ``process_frame`` result — no manual update calls needed.

        Returns the ``viser.ViserServer`` for further customization.

        Requires ``pip install viser trimesh``.
        """
        import viser
        import viser.transforms as vtf

        server = viser.ViserServer(port=port)
        self._viser_server = server

        # World frame
        server.scene.add_frame(
            "/world", axes_length=0.05, axes_radius=0.002, origin_radius=0.0,
        )

        # Camera frame
        T_wc = self.extrinsic if self.extrinsic is not None else np.eye(4)
        cam_wxyz = tuple(vtf.SO3.from_matrix(T_wc[:3, :3]).wxyz)
        cam_pos = tuple(T_wc[:3, 3])
        server.scene.add_frame(
            "/camera", wxyz=cam_wxyz, position=cam_pos,
            axes_length=0.04, axes_radius=0.002, origin_radius=0.0,
        )

        # Ground grid
        grid_half = 0.3
        grid_step = 0.05
        grid_lines = []
        n = int(grid_half / grid_step)
        for i in range(-n, n + 1):
            p = i * grid_step
            grid_lines.append([[p, -grid_half, 0], [p, grid_half, 0]])
            grid_lines.append([[-grid_half, p, 0], [grid_half, p, 0]])
        server.scene.add_line_segments(
            "/ground_grid",
            points=np.array(grid_lines, dtype=np.float32),
            colors=(80, 80, 80),
            line_width=1.0,
        )

        # Textured mesh
        if self.model_dir is not None:
            from pathlib import Path
            obj_path = Path(self.model_dir) / "mujoco" / "cube.obj"
            if obj_path.exists():
                import trimesh
                mesh = trimesh.load(str(obj_path))
                server.scene.add_mesh_trimesh("/object/mesh", mesh)

        # Object axes
        axis_len = float(max(self.config.box_dims)) / 1000.0 * 0.6
        server.scene.add_frame(
            "/object/axes", axes_length=axis_len, axes_radius=0.002,
            origin_radius=0.0,
        )

        # GUI sidebar
        server.gui.set_panel_label("AprilCube")
        cam_folder = server.gui.add_folder("Camera Feed")
        with cam_folder:
            self._viser_gui_image = server.gui.add_image(
                np.zeros((240, 320, 3), dtype=np.uint8),
                label="Detection",
                format="jpeg",
                jpeg_quality=70,
            )
            self._viser_gui_status = server.gui.add_markdown(
                "*Waiting for detection...*"
            )

        # Start background render thread
        t = threading.Thread(target=self._viser_loop, daemon=True)
        t.start()

        return server

    def _viser_loop(self) -> None:
        """Background thread: render latest detection to viser at ~30 fps."""
        import viser.transforms as vtf

        server = self._viser_server
        while True:
            # Wait for a new frame
            counter = self._frame_counter
            if counter == self._viser_rendered_counter:
                time.sleep(0.01)
                continue
            self._viser_rendered_counter = counter

            with self._latest_lock:
                result = self._latest_result
                frame = self._latest_frame
            if result is None or frame is None:
                time.sleep(0.01)
                continue

            fps = self._fps

            # Update object pose
            T = self.world_pose(result)
            if T is not None:
                T_m = T.copy()
                T_m[:3, 3] /= 1000.0  # mm -> meters
                wxyz = tuple(vtf.SO3.from_matrix(T_m[:3, :3]).wxyz)
                pos = tuple(T_m[:3, 3])
                server.scene.add_frame(
                    "/object", wxyz=wxyz, position=pos,
                    axes_length=0.0, origin_radius=0.0,
                )

            # 2D overlay -> GUI sidebar
            vis = self.draw_result(frame, result)
            cv2.putText(vis, f"FPS: {fps:.0f}", (10, 30),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
            vis_rgb = cv2.cvtColor(vis, cv2.COLOR_BGR2RGB)
            if self._viser_gui_image is not None:
                self._viser_gui_image.image = vis_rgb

            # Status text
            if self._viser_gui_status is not None:
                if result["success"]:
                    t = result["tvec"].flatten()
                    faces = ", ".join(sorted(result["visible_faces"]))
                    self._viser_gui_status.content = (
                        f"**Tags:** {result['n_tags']} | "
                        f"**Faces:** {faces}\n\n"
                        f"**Reproj:** {result['reproj_error']:.2f}px | "
                        f"**FPS:** {fps:.0f}\n\n"
                        f"**T:** [{t[0]:.1f}, {t[1]:.1f}, {t[2]:.1f}] mm"
                    )
                else:
                    self._viser_gui_status.content = (
                        f"*No detection* | **FPS:** {fps:.0f}"
                    )



# ---------------------------------------------------------------------------
# Camera intrinsics
# ---------------------------------------------------------------------------
def load_camera_params(args, frame_shape: tuple[int, ...]
                       ) -> tuple[np.ndarray, np.ndarray]:
    """Load camera matrix and distortion coefficients."""
    if args.calib:
        with open(args.calib) as f:
            data = json.load(f)
        camera_matrix = np.array(data["camera_matrix"], dtype=np.float64)
        dist_coeffs = np.array(data.get("dist_coeffs", [0, 0, 0, 0, 0]), dtype=np.float64)
        return camera_matrix, dist_coeffs

    h, w = frame_shape[:2]
    if args.fx is not None:
        fx = args.fx
        fy = args.fy if args.fy is not None else args.fx
        cx = args.cx if args.cx is not None else w / 2
        cy = args.cy if args.cy is not None else h / 2
    else:
        # Rough default: assume FOV ~60deg -> fx ~ w
        fx = fy = float(w)
        cx, cy = w / 2, h / 2
        print("Warning: no calibration provided, using default intrinsics "
              f"(fx=fy={fx:.0f}, cx={cx:.0f}, cy={cy:.0f})", file=sys.stderr)

    camera_matrix = np.array([
        [fx, 0, cx],
        [0, fy, cy],
        [0, 0, 1],
    ], dtype=np.float64)
    dist_coeffs = np.zeros(5, dtype=np.float64)
    return camera_matrix, dist_coeffs


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(
        description="Detect ArUco/AprilTag cube and estimate 6-DOF pose.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="Examples:\n"
        "  %(prog)s --cube my_cube/config.json\n"
        "  %(prog)s --cube my_cube/config.json --camera 1\n"
        "  %(prog)s --cube my_cube/config.json --image photo.jpg --viz\n"
        "  %(prog)s --cube my_cube/config.json --calib calib.json --viz\n",
    )

    # Cube config
    parser.add_argument("--cube", type=str, required=True,
                        help="Path to config.json from generate_cube.py")

    # Input source (optional — defaults to webcam 0)
    input_grp = parser.add_mutually_exclusive_group()
    input_grp.add_argument("--camera", type=int, default=None, help="Camera index (default: 0)")
    input_grp.add_argument("--image", type=str, default=None, help="Image file path")
    input_grp.add_argument("--video", type=str, default=None, help="Video file path")

    # Camera intrinsics
    parser.add_argument("--calib", type=str, default=None, help="Calibration JSON file")
    parser.add_argument("--fx", type=float, default=None, help="Focal length X (pixels)")
    parser.add_argument("--fy", type=float, default=None, help="Focal length Y (pixels)")
    parser.add_argument("--cx", type=float, default=None, help="Principal point X")
    parser.add_argument("--cy", type=float, default=None, help="Principal point Y")

    # Options
    parser.add_argument("--no-filter", action="store_true", help="Disable temporal smoothing")
    parser.add_argument("--viz", action="store_true", help="Show debug visualization window")

    args = parser.parse_args()

    # Load cube config from JSON
    config, face_id_sets = load_cube_config(args.cube)
    bx, by, bz = config.box_dims
    print(f"Cube: {bx:.4g} x {by:.4g} x {bz:.4g} mm, "
          f"{len(config.tag_ids)} tags ({config.dict_name}), "
          f"cell={config.cell_size:.4g}mm")

    # Determine input source — default to webcam 0
    is_stream = args.image is None
    if args.image is not None:
        frame = cv2.imread(args.image)
        if frame is None:
            print(f"Error: cannot read {args.image}", file=sys.stderr)
            sys.exit(1)
        cap = None
    else:
        if args.video is not None:
            source = args.video
        else:
            source = args.camera if args.camera is not None else 0
        cap = cv2.VideoCapture(source)
        if not cap.isOpened():
            print(f"Error: cannot open camera/video {source}", file=sys.stderr)
            sys.exit(1)
        ret, frame = cap.read()
        if not ret:
            print("Error: cannot read first frame", file=sys.stderr)
            sys.exit(1)
        src_label = f"camera {source}" if args.video is None else args.video
        print(f"Input: {src_label} ({frame.shape[1]}x{frame.shape[0]})")

    # Load camera intrinsics
    camera_matrix, dist_coeffs = load_camera_params(args, frame.shape)
    print(f"Camera: fx={camera_matrix[0,0]:.1f} fy={camera_matrix[1,1]:.1f} "
          f"cx={camera_matrix[0,2]:.1f} cy={camera_matrix[1,2]:.1f}")

    # Create estimator
    enable_filter = not args.no_filter and is_stream
    estimator = CubePoseEstimator(config, face_id_sets, camera_matrix, dist_coeffs, enable_filter)

    # --- Single image mode ---
    if cap is None:
        result = estimator.process_frame(frame)
        if result["success"]:
            r = result["rvec"].flatten()
            t = result["tvec"].flatten()
            print(f"Pose: rvec=[{r[0]:.4f}, {r[1]:.4f}, {r[2]:.4f}] "
                  f"tvec=[{t[0]:.1f}, {t[1]:.1f}, {t[2]:.1f}] mm")
            print(f"  reproj={result['reproj_error']:.2f}px, "
                  f"tags={result['n_tags']}/{len(config.tag_ids)}, "
                  f"faces={','.join(sorted(result['visible_faces']))}")
        else:
            print("No pose detected.")

        if args.viz:
            vis = estimator.draw_result(frame, result)
            cv2.imshow("detect_cube", vis)
            print("Press any key to exit.")
            cv2.waitKey(0)
            cv2.destroyAllWindows()
        return

    # --- Video / camera loop ---
    fps_timer = time.time()
    fps_count = 0
    fps_display = 0.0
    is_live = args.video is None
    video_fps = cap.get(cv2.CAP_PROP_FPS) if not is_live else 0
    frame_idx = 0

    while True:
        if frame is None:
            ret, frame = cap.read()
            if not ret:
                break

        if is_live:
            ts = time.monotonic()
        else:
            ts = frame_idx / video_fps if video_fps > 0 else frame_idx / 30.0
        frame_idx += 1

        result = estimator.process_frame(frame, timestamp=ts)

        # FPS counter
        fps_count += 1
        elapsed = time.time() - fps_timer
        if elapsed >= 1.0:
            fps_display = fps_count / elapsed
            fps_count = 0
            fps_timer = time.time()

        if result["success"]:
            r = result["rvec"].flatten()
            t = result["tvec"].flatten()
            faces = ",".join(sorted(result["visible_faces"]))
            print(f"\rrvec=[{r[0]:+.3f},{r[1]:+.3f},{r[2]:+.3f}] "
                  f"tvec=[{t[0]:+.0f},{t[1]:+.0f},{t[2]:+.0f}]mm "
                  f"err={result['reproj_error']:.1f}px "
                  f"tags={result['n_tags']} faces={faces} "
                  f"fps={fps_display:.0f}",
                  end="", flush=True)

        if args.viz:
            vis = estimator.draw_result(frame, result)
            cv2.putText(vis, f"FPS: {fps_display:.0f}", (10, 30),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
            cv2.imshow("detect_cube", vis)
            key = cv2.waitKey(1) & 0xFF
            if key == 27 or key == ord("q"):
                break

        frame = None  # read next frame on next iteration

    print()
    cap.release()
    if args.viz:
        cv2.destroyAllWindows()


if __name__ == "__main__":
    main()
